Repository api3dao/api3-docs, pull requests merged in 2021-11, with the labels that each got.

#381 Describe config action in dev/github-actions.md
  .github/workflows/scheduled_config_pr.yaml
  docs/dev/github-actions.md
  docs/dev/plugins.md
Labels: v0.2

#382 Add LICENSE
  LICENSE
Labels: v0.2

#383 Removed occurrences of the word we.
  docs/airnode/v0.2/concepts/authorization.md
  docs/airnode/v0.2/concepts/sponsor.md
  docs/airnode/v0.2/grp-developers/guides/smart-contracts-platform/is-my-platform-compatible.md
  docs/airnode/v0.2/grp-developers/self-serve-platforms.md
  docs/airnode/v0.2/grp-providers/airnode/design-philosophy.md
  docs/airnode/v0.2/grp-providers/airnode/implementation.md
  docs/airnode/v0.2/grp-providers/docker/client-image.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.2/introduction/why-use-airnode.md
  docs/airnode/v0.2/reference/deployment-files/secrets-env.md
  docs/airnode/v0.2/reference/packages/README.md
  docs/api3/README.md
  docs/api3/introduction/contributing.md
  docs/api3/introduction/dapis.md
Labels: v0.2

#385 Decrease lychee concurrency to reduce 429 errors
  .github/workflows/lychee.toml
Labels: v0.2

#387 Update missed docs for prettier formatting
  docs/airnode/v0.2/grp-developers/code/create-template-id.js
  docs/airnode/v0.2/reference/specifications/ois.md
  docs/airnode/v0.2/reference/specifications/reserved-parameters.md
  docs/airnode/v0.3/grp-developers/code/create-template-id.js
  docs/airnode/v0.3/grp-developers/using-templates.md
  docs/airnode/v0.3/reference/specifications/ois.md
  docs/airnode/v0.3/reference/specifications/reserved-parameters.md
  docs/dev-airnode/README.md
  docs/dev-airnode/sidebar.js
Labels: v0.3

#388 Type "unit" should be "uint", in step 6
  docs/dao-members/dashboard/proposals.md
Labels: bug

#389 Use <a> tags for pdf viewing to local pdf file
  docs/airnode/v0.2/README.md
  docs/airnode/v0.3/README.md
  docs/api3/README.md
  docs/api3/introduction/contributing.md
  docs/api3/introduction/dapis.md
  docs/api3/introduction/first-party-oracles.md
  docs/dao-members/introduction/api3-dao.md
  docs/dao-members/introduction/dao-pool.md
Labels: v0.3

#390 AN-318 docker instructions
  docs/.vuepress/redirects
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.2/grp-providers/tutorial/README.md
  docs/airnode/v0.2/grp-providers/tutorial/config-json.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/tutorial/README.md
  docs/airnode/v0.3/grp-providers/tutorial/config-json.md
Labels: v0.2

#391 AN-318 Docker Instructions
  docs/airnode/v0.2/grp-providers/docker/README.md
  docs/airnode/v0.2/grp-providers/docker/client-image.md
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.2/reference/deployment-files/config-json.md
  docs/airnode/v0.2/reference/templates/config-json.md
  docs/airnode/v0.3/grp-providers/docker/README.md
  docs/airnode/v0.3/grp-providers/docker/client-image.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.3/reference/templates/config-json.md
Labels: v0.2, v0.3

#393 AN-327 manual airnode removal
  docs/.vuepress/components/DeleteAirnodeAws.vue
  docs/.vuepress/components/DockerImageVersions.vue
  docs/.vuepress/components/ExternalLinkImage.vue
  docs/airnode/v0.2/grp-providers/docker/README.md
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.2/grp-providers/tutorial/README.md
  docs/airnode/v0.3/grp-providers/docker/README.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/tutorial/README.md
Labels: v0.2, v0.3

#394 nodeVersion adjustments.
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.2/reference/deployment-files/receipt-json.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.3/reference/deployment-files/receipt-json.md
  docs/airnode/v0.3/reference/examples/config-local.json
  docs/airnode/v0.3/reference/examples/config-provider.json
Labels: v0.2, v0.3

#395 2021-11-08 admin image
  docs/.vuepress/components/DeleteAirnodeAws.vue
  docs/.vuepress/components/DockerImageVersions.vue
  docs/airnode/v0.2/grp-developers/self-serve-platforms.md
  docs/airnode/v0.2/grp-providers/docker/README.md
  docs/airnode/v0.2/reference/examples/config-json.md
  docs/airnode/v0.3/grp-providers/docker/README.md
  docs/airnode/v0.3/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.3/reference/packages/admin-cli-commands.md
  docs/airnode/v0.3/sidebar.js
Labels: v0.2, v0.3

#396 AN-222 Add validator docs
  docs/airnode/v0.2/grp-providers/validator.md
Labels: v0.3

#397 2021-11-09 cleanup post prs
  docs/airnode/v0.2/grp-developers/self-serve-platforms.md
  docs/airnode/v0.2/reference/examples/config-local.json
  docs/airnode/v0.2/reference/examples/config-provider.json
  docs/airnode/v0.2/reference/packages/admin-cli-commands.md
  docs/airnode/v0.3/grp-providers/validator.md
  docs/airnode/v0.3/reference/packages/admin-cli-commands.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.3/sidebar.js
Labels: v0.2, v0.3

#398 Skip airnode v0.3 link checking for now
  .github/workflows/check-links-imgs.yaml
Labels: v0.2, v0.3

#399 Part of AN-334 prep work
  archived/airnode/v.03/guides/smart-contracts-platform/is-my-platform-compatible.md
  archived/airnode/v.03/guides/smart-contracts-platform/self-serve-integration.md
  archived/airnode/v0.2/README.md
  archived/airnode/v0.2/_hold/README.md
  archived/airnode/v0.2/_hold/hardhat-starter.md
  archived/airnode/v0.2/_hold/ois.md
  archived/airnode/v0.2/_hold/post-processing.md
  archived/airnode/v0.2/cli-commands copy.md
  archived/airnode/v0.2/config-json.md
  archived/airnode/v0.2/deployer-commands.md
  archived/airnode/v0.2/depr-config-examples/authorizers-json.md
  archived/airnode/v0.2/depr-config-examples/config-example-json.md
  archived/airnode/v0.2/depr-config-examples/example-env.md
  archived/airnode/v0.2/depr-config-examples/security-json.md
  archived/airnode/v0.2/depr-config-json.md
  archived/airnode/v0.2/depr-dashboard/dao.md
  archived/airnode/v0.2/depr-dashboard/overview.md
  archived/airnode/v0.2/depr-dashboard/pool.md
  archived/airnode/v0.2/depr-dashboard/voting.md
  archived/airnode/v0.2/depr-developing-a-client-contract.md
  archived/airnode/v0.2/depr-docker/client-image.md
  archived/airnode/v0.2/depr-docker/deployer-image.md
  archived/airnode/v0.2/depr-faqs.md
  archived/airnode/v0.2/depr-grp-providers/api-integration-orig.md
  archived/airnode/v0.2/depr-grp-providers/apply-auth-notes.md
  archived/airnode/v0.2/depr-grp-providers/configuring-airnode-orig.md
  archived/airnode/v0.2/depr-grp-providers/deploying-airnode-orig.md
  archived/airnode/v0.2/depr-grp-providers/setting-authorizers-orig.md
  archived/airnode/v0.2/depr-requester/creating-a-requester.md
  archived/airnode/v0.2/depr-requester/developing-a-client-contract.md
  archived/airnode/v0.2/depr-rewards.md
  archived/airnode/v0.2/depr-security-json.md
  archived/airnode/v0.2/depr-security-json2.md
  archived/airnode/v0.2/depr-tokens.md
  archived/airnode/v0.2/depr-voting.md
  archived/airnode/v0.2/guides/smart-contracts-platform/is-my-platform-compatible.md
  archived/airnode/v0.2/guides/smart-contracts-platform/self-serve-integration.md
  archived/airnode/v0.2/old-airnode-starter-files/airnode-starter.md
  archived/airnode/v0.2/old-airnode-starter-files/authorizers-json.md
  archived/airnode/v0.2/old-airnode-starter-files/config-json.md
  archived/airnode/v0.2/old-airnode-starter-files/example-config-airnode-starter.json
  archived/airnode/v0.2/old-airnode-starter-files/receipt-json.md
  archived/airnode/v0.2/old-airnode-starter-files/secrets-env.md
  archived/airnode/v0.2/old-airnode-starter-files/tutorial-authorizers.json
  archived/airnode/v0.2/old-airnode-starter-files/tutorial-config.json
  archived/airnode/v0.2/old-airnode-starter-files/tutorial-receipt.json
  archived/airnode/v0.2/old-airnode-starter-files/tutorial-secrets.env
  archived/airnode/v0.2/rrp-flowdiagram.md
  archived/airnode/v0.2/sponsor-wallet.md
  archived/airnode/v0.2/sponsorship.md
  archived/airnode/v0.2/template-config.json-depr
  archived/airnode/v0.2/templates-depr/config-json.md
  archived/airnode/v0.2/templates-depr/ois-json.md
  archived/airnode/v0.2/templates-depr/security-json.md
  docs/airnode/v0.2/sidebar.js
  docs/airnode/v0.3/sidebar.js
Labels: v0.2, v0.3

#400 AN-335 pre-alpha references
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.2/reference/specifications/reserved-parameters.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/dev/versioning.md
Labels: v0.2, v0.3

#401 api3/deployer renamed api3/airnode-deployer
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
Labels: v0.2, v0.3

#402 Fix CI
  .github/workflows/lychee.toml
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.2/grp-providers/validator.md
Labels: v0.3

#403 2021-11-11 v3 examples
  docs/airnode/v0.2/grp-providers/docker/client-image.md
  docs/airnode/v0.3/grp-providers/docker/client-image.md
  docs/airnode/v0.3/reference/examples/config-json.md
  docs/airnode/v0.3/reference/packages/admin-cli-commands.md
Labels: v0.3

#404 Use class for divider
  docs/.vuepress/components/SubSites.vue
Labels: v0.3

#405 AN-222.1 An early pass at the validator
  docs/airnode/v0.3/reference/packages/README.md
  docs/airnode/v0.3/reference/packages/airnode-validator.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.3/sidebar.js
Labels: v0.3

#407 AN-222.2 Validator
  docs/airnode/v0.2/reference/specifications/reserved-parameters.md
  docs/airnode/v0.3/reference/packages/airnode-validator.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.3/sidebar.js
Labels: v0.3

#410 2021-11-14 rename admin-cli-commands.md
  docs/airnode/v0.3/concepts/README.md
  docs/airnode/v0.3/concepts/airnode.md
  docs/airnode/v0.3/concepts/authorization.md
  docs/airnode/v0.3/concepts/endpoint.md
  docs/airnode/v0.3/concepts/sponsor.md
  docs/airnode/v0.3/grp-developers/fees.md
  docs/airnode/v0.3/grp-developers/requesters-sponsors.md
  docs/airnode/v0.3/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/apply-auth.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.3/reference/packages/README.md
  docs/airnode/v0.3/reference/packages/adapter.md
  docs/airnode/v0.3/reference/packages/admin-cli.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.3/sidebar.js
Labels: v0.3

#413 Implement timestamp value for _type parameter
  docs/airnode/v0.3/reference/specifications/reserved-parameters.md
Labels: v0.3

#415 Revert "Refactor to streamline Quick Deploy Demo"
  docs/airnode/v0.2/grp-providers/tutorial/README.md
  docs/airnode/v0.2/grp-providers/tutorial/aws-env.md
  docs/airnode/v0.2/grp-providers/tutorial/config-json.md
  docs/airnode/v0.2/grp-providers/tutorial/quick-deploy-demo/aws.env
  docs/airnode/v0.2/grp-providers/tutorial/quick-deploy-demo/config/config.json
  docs/airnode/v0.2/grp-providers/tutorial/quick-deploy-demo/config/secrets.env
  docs/airnode/v0.2/grp-providers/tutorial/secrets-env.md
  docs/airnode/v0.3/grp-providers/tutorial/README.md
  docs/airnode/v0.3/grp-providers/tutorial/aws-env.md
  docs/airnode/v0.3/grp-providers/tutorial/config-json.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-demo/aws.env
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-demo/config/config.json
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-demo/config/secrets.env
  docs/airnode/v0.3/grp-providers/tutorial/secrets-env.md
Labels: v0.3

#416 AN-222.3
  docs/airnode/v0.3/grp-providers/tutorial/README.md
  docs/airnode/v0.3/reference/packages/validator.md
Labels: v0.3

#418 Final pass at the validator, pending review by Jakub
  docs/airnode/v0.3/reference/packages/validator.md
Labels: v0.3

#419 AN-222.5
  archived/airnode/_hold/README.md
  archived/airnode/_hold/hardhat-starter.md
  archived/airnode/_hold/ois.md
  archived/airnode/_hold/post-processing.md
  docs/.vuepress/redirects
  docs/airnode/v0.3/reference/packages/validator.md
Labels: v0.3

#421 AN-323: First pass at the Airnode Quick Deploy Local
  docs/airnode/v0.3/assets/images/docker-cli.png
  docs/airnode/v0.3/grp-providers/tutorial/README.md
  docs/airnode/v0.3/grp-providers/tutorial/aws-env.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/aws-env.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/config-json.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/secrets-env.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/config-json.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/secrets-env.md
  docs/airnode/v0.3/sidebar.js
Labels: v0.3

#422 AN-323.2
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.3.zip
  docs/.vuepress/public/zip-files/quick-deploy-local-v0.3.zip
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/aws-env.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/config-json.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/secrets-env.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/src/aws.env
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/src/config.json
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/src/secrets.env
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/config-json.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/secrets-env.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/src/config.json
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-local/src/secrets.env
  libs/zip-files.js
  package.json
  yarn.lock
Labels: v0.3

#423 2021-11-19 link validator and /dev content
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.3.zip
  docs/.vuepress/public/zip-files/quick-deploy-local-v0.3.zip
  docs/dev/README.md
  docs/dev/link-validator.md
  docs/dev/quirks.md
  docs/dev/sidebar.js
  docs/dev/versioning.md
  docs/dev/zip-files.md
  libs/link-validator.js
  libs/zip-files.js
Labels: v0.3

#425 Add response clarification to Quick Deploy Container tutorial
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-container/README.md
Labels: v0.3

#426 Update white paper links to v1.0.2
  docs/.vuepress/public/api3-whitepaper-v1.0.2.pdf
  docs/airnode/v0.2/README.md
  docs/airnode/v0.3/README.md
  docs/api3/README.md
  docs/api3/introduction/contributing.md
  docs/api3/introduction/dapis.md
  docs/api3/introduction/first-party-oracles.md
  docs/dao-members/introduction/api3-dao.md
  docs/dao-members/introduction/dao-pool.md
Labels: v0.3

#427 AN-360.1
  docs/.vuepress/redirects
  libs/link-validator.js
Labels: v0.3

#429 AN-360.2 Added images to the checks.
  docs/dev/link-validator.md
  libs/link-validator.js
  package.json
Labels: v0.3

#431 Proposal creation signature warning
  docs/dao-members/dashboard/proposals.md
Labels: v0.3

#432 Add link to license
  docs/README.md
Labels: v0.3

#434 Fix minor typo
  docs/airnode/v0.3/grp-providers/docker/admin-cli-image.md
Labels: v0.3

#435 Changes to the interpolation implementation
  docs/airnode/v0.3/reference/packages/validator.md
Labels: v0.3

#437 AN-362 Touch up on some of the sample commands
  docs/airnode/v0.3/reference/packages/deployer.md
Labels: v0.3

#438 Redirects for airnode-deployer
  docs/.vuepress/redirects
Labels: v0.3

#440 Prettier formatting issues.
  docs/airnode/v0.2/concepts/request.md
  docs/airnode/v0.3/concepts/request.md
Labels: v0.3

#442 AN-362.3 deployer
  docs/.vuepress/styles/index.styl
  docs/airnode/v0.3/reference/packages/deployer.md
Labels: v0.3

#443 2021-11-30 requester response cnt
  docs/airnode/v0.2/grp-developers/call-an-airnode.md
  docs/airnode/v0.3/grp-developers/call-an-airnode.md
Labels: v0.3
