Repository api3dao/api3-docs, pull requests merged in 2021-10, with the labels that each got.

#264 Fixed the icon flickering when the SPA loads
  docs/.vuepress/components/SubSites.vue
Labels: v0.1.0

#266 Added diagram to airnode-auth.md and intro text
  docs/airnode/next/assets/diagrams/concepts-airnode-auth.drawio
  docs/airnode/next/assets/images/concepts-airnode-auth.png
  docs/airnode/next/concepts/airnode-auth.md
  docs/airnode/pre-alpha/figures/concepts-airnode-auth.drawio
  docs/airnode/pre-alpha/figures/concepts-airnode-auth.png
  docs/airnode/pre-alpha/protocols/request-response/airnode-auth.md
Labels: v0.1.0

#268 AN-243_AN-234
  archived/airnode/next/README.md
  archived/airnode/next/cli-commands copy.md
  archived/airnode/next/depr-config-examples/authorizers-json.md
  archived/airnode/next/depr-config-examples/config-example-json.md
  archived/airnode/next/depr-config-examples/example-env.md
  archived/airnode/next/depr-config-examples/security-json.md
  archived/airnode/next/depr-config-json.md
  archived/airnode/next/depr-dashboard/dao.md
  archived/airnode/next/depr-dashboard/overview.md
  archived/airnode/next/depr-dashboard/pool.md
  archived/airnode/next/depr-dashboard/voting.md
  archived/airnode/next/depr-developing-a-client-contract.md
  archived/airnode/next/depr-docker/client-image.md
  archived/airnode/next/depr-docker/deployer-image.md
  archived/airnode/next/depr-faqs.md
  archived/airnode/next/depr-grp-providers/api-integration-orig.md
  archived/airnode/next/depr-grp-providers/configuring-airnode-orig.md
  archived/airnode/next/depr-grp-providers/deploying-airnode-orig.md
  archived/airnode/next/depr-grp-providers/setting-authorizers-orig.md
  archived/airnode/next/depr-requester/creating-a-requester.md
  archived/airnode/next/depr-requester/developing-a-client-contract.md
  archived/airnode/next/depr-rewards.md
  archived/airnode/next/depr-security-json.md
  archived/airnode/next/depr-security-json2.md
  archived/airnode/next/depr-tokens.md
  archived/airnode/next/depr-voting.md
  archived/airnode/next/rrp-flowdiagram.md
  archived/airnode/next/sponsor-wallet.md
  archived/airnode/next/sponsorship.md
  archived/airnode/next/template-config.json-depr
  archived/airnode/next/templates-depr/config-json.md
  archived/airnode/next/templates-depr/ois-json.md
  archived/airnode/next/templates-depr/security-json.md
  archived/airnode/pre-alpha/members/README.md
  archived/airnode/pre-alpha/members/contract-architecture/dao.md
  archived/airnode/pre-alpha/members/contract-architecture/overview.md
  archived/airnode/pre-alpha/members/contract-architecture/pool.md
  archived/airnode/pre-alpha/members/contract-architecture/voting.md
  archived/airnode/pre-alpha/members/dao-tracker.md
  archived/airnode/pre-alpha/members/governance/proposals.md
  archived/airnode/pre-alpha/members/governance/voting.md
  archived/airnode/pre-alpha/members/staking/pool-claims.md
  archived/airnode/pre-alpha/members/staking/rewards.md
  archived/airnode/pre-alpha/members/staking/voting-power.md
  archived/airnode/pre-alpha/members/videos.md
  archived/dev/sidebarHeader.md
  docs/airnode/next/sidebar.js
Labels: v0.1.0

#269 AN-241: Augment and clarify proposal steps
  docs/dao-members/dashboard/proposals.md
Labels: v0.1.0

#272 AN-234_2021-10-02.2
  archived/airnode/next/_hold/README.md
  archived/airnode/next/_hold/hardhat-starter.md
  archived/airnode/next/_hold/ois.md
  archived/airnode/next/_hold/post-processing.md
  archived/airnode/next/depr-grp-providers/apply-auth-notes.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-auth.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/removing-airnode.md
  docs/airnode/next/sidebar.js
Labels: v0.1.0

#276 Changes for docker and deployment
  docs/airnode/next/grp-providers/docker/README.md
  docs/airnode/next/grp-providers/docker/client-image.md
  docs/airnode/next/grp-providers/docker/deployer-image.md
  docs/airnode/next/grp-providers/tutorial/quick-demo/README.md
  docs/airnode/next/grp-providers/tutorial/quick-demo/aws.env.md
  docs/airnode/next/grp-providers/tutorial/quick-demo/config.json.md
  docs/airnode/next/grp-providers/tutorial/quick-demo/secrets.env.md
  docs/airnode/next/sidebar.js
Labels: v0.1.0

#283 There is always something that got missed.
  docs/airnode/next/grp-providers/tutorial/README.md
Labels: v1.0.0

#284 Minor content enhancements
  docs/airnode/next/grp-providers/docker/deployer-image.md
Labels: v1.0.0

#288 AN-234.8
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-auth.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/next/grp-providers/tutorial/README.md
  docs/airnode/next/reference/deployment-files/aws-env.md
  docs/airnode/next/reference/deployment-files/config-json.md
  docs/airnode/next/reference/deployment-files/overview.md
  docs/airnode/next/sidebar.js
Labels: v1.0.0

#289 Sponsor wallet xpub error messages
  docs/airnode/next/concepts/README.md
  docs/airnode/next/concepts/airnode.md
  docs/airnode/next/concepts/request.md
  docs/airnode/next/concepts/sponsor.md
  docs/airnode/next/grp-developers/call-an-airnode.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/next/reference/admin-cli-commands.md
  docs/airnode/next/reference/deployment-files/receipt-json.md
Labels: documentation, v1.0.0

#291 Deployer images change for: Build an Airnode
  docs/.vuepress/components/DeployerPermissionsWarning.vue
  docs/airnode/next/grp-providers/docker/deployer-image.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/next/grp-providers/tutorial/README.md
  docs/airnode/next/sidebar.js
Labels: v1.0.0

#294 HTTP Gateway cleanup
  docs/.vuepress/components/DeployerPermissionsWarning.vue
  docs/airnode/next/assets/diagrams/config-json.drawio
  docs/airnode/next/assets/images/config-json.png
  docs/airnode/next/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/next/grp-providers/tutorial/README.md
  docs/airnode/next/grp-providers/tutorial/config.json.md
  docs/airnode/next/reference/specifications/ois.md
Labels: v1.0.0

#296 Remove AWS credential from secrets.env.
  docs/airnode/next/grp-providers/guides/build-an-airnode/api-integration.md
Labels: v1.0.0

#301 AN-269.1
  docs/.vuepress/redirects
  docs/airnode/next/assets/diagrams/api-integration-ois.drawio
  docs/airnode/next/assets/diagrams/api-provider-overview.drawio
  docs/airnode/next/assets/diagrams/developer-overview.drawio
  docs/airnode/next/assets/diagrams/gateway.drawio
  docs/airnode/next/assets/diagrams/requesters-sponsors-1.drawio
  docs/airnode/next/assets/images/api-integration-ois.png
  docs/airnode/next/assets/images/api-provider-overview.png
  docs/airnode/next/assets/images/developer-overview.png
  docs/airnode/next/assets/images/gateway.png
  docs/airnode/next/assets/images/requesters-sponsors-1.png
  docs/airnode/next/grp-providers/README.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/http-gateway.md
Labels: v1.0.0

#302 Cleanup of the last three issues with authorization.md
  docs/airnode/next/assets/diagrams/concepts-relay-metadata.drawio
  docs/airnode/next/assets/images/concepts-relay-metadata.png
  docs/airnode/next/concepts/authorization.md
Labels: v1.0.0

#309 Sub-site for API3
  docs/.vuepress/components/SubSites.vue
  docs/.vuepress/config.js
  docs/airnode/next/README-orig.md
  docs/airnode/next/README.md
  docs/airnode/next/introduction/apis.md
  docs/airnode/next/introduction/blog-posts.md
  docs/airnode/next/introduction/contributing.md
  docs/airnode/next/introduction/dapis.md
  docs/airnode/next/introduction/decentrally-governed-oracle-networks.md
  docs/airnode/next/introduction/first-party-oracles.md
  docs/airnode/next/introduction/why-use-airnode.md
  docs/airnode/next/reference/depr-code/template-aws.env
  docs/airnode/next/reference/depr-code/template-config.json
  docs/airnode/next/reference/depr-code/template-ois.json
  docs/airnode/next/reference/depr-code/template-secrets.env
  docs/airnode/next/reference/examples/aws-env.md
  docs/airnode/next/reference/examples/config-json.md
  docs/airnode/next/reference/examples/secrets-env.md
  docs/airnode/next/reference/templates/aws-env.md
  docs/airnode/next/reference/templates/config-json.md
  docs/airnode/next/reference/templates/ois-json.md
  docs/airnode/next/reference/templates/secrets-env.md
  docs/airnode/next/sidebar.js
  docs/airnode/pre-alpha/README.md
  docs/airnode/pre-alpha/introduction/why-use-airnode.md
  docs/airnode/pre-alpha/sidebar.js
  docs/api3/README.md
  docs/api3/apis.md
  docs/api3/blog-posts.md
  docs/api3/contributing.md
  docs/api3/dapis.md
  docs/api3/decentrally-governed-oracle-networks.md
  docs/api3/first-party-oracles.md
  docs/api3/images/api3.png
  docs/api3/sidebar.js
  docs/common/the-airnode.md
  docs/common/why-use-airnode.md
Labels: v1.0.0

#313 Skip coingecko url returning 503 status code
  .github/workflows/lychee.toml
Labels: v1.0.0

#318 Adds more links to doc references and minor improvements
  docs/airnode/next/reference/admin-cli-commands.md
Labels: documentation, v1.0.0

#321 AN-225.5
  docs/airnode/next/assets/diagrams/airnode-is-2-parts.drawio
  docs/airnode/next/assets/diagrams/call-an-airnode.drawio
  docs/airnode/next/assets/diagrams/concepts-request.drawio
  docs/airnode/next/assets/diagrams/config-json.drawio
  docs/airnode/next/assets/diagrams/developer-overview.drawio
  docs/airnode/next/assets/images/airnode-is-2-parts.png
  docs/airnode/next/assets/images/call-an-airnode.png
  docs/airnode/next/assets/images/concepts-request.png
  docs/airnode/next/assets/images/config-json.png
  docs/airnode/next/assets/images/developer-overview.png
  docs/airnode/next/concepts/request.md
  docs/airnode/next/grp-developers/README.md
  docs/airnode/next/grp-developers/call-an-airnode.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/configuring-airnode.md
Labels: v1.0.0

#328 Add security field
  docs/airnode/v1.0/reference/specifications/ois.md
Labels: v1.0

#329 Update scheme descriptions
  docs/airnode/v1.0/reference/specifications/ois.md
Labels: v1.0

#330 Corrections to the field requirements
  docs/airnode/v1.0/reference/specifications/ois.md
Labels: v1.0

#335 Remove security field from OIS
  docs/airnode/v1.0/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v1.0/grp-providers/tutorial/config-json.md
  docs/airnode/v1.0/reference/depr-code/template-aws.env
  docs/airnode/v1.0/reference/depr-code/template-config.json
  docs/airnode/v1.0/reference/depr-code/template-ois.json
  docs/airnode/v1.0/reference/depr-code/template-secrets.env
  docs/airnode/v1.0/reference/templates/config-json.md
  docs/airnode/v1.0/reference/templates/ois-json.md
Labels: v1.0

#339 Diagram updates
  docs/airnode/v1.0/assets/diagrams/concepts-authorizers.drawio
  docs/airnode/v1.0/assets/diagrams/concepts-relay-metadata.drawio
  docs/airnode/v1.0/assets/images/concepts-authorizers.png
  docs/airnode/v1.0/assets/images/concepts-relay-metadata.png
  docs/airnode/v1.0/concepts/authorization.md
  docs/airnode/v1.0/concepts/chain-providers.md
  docs/airnode/v1.0/grp-providers/guides/build-an-airnode/configuring-airnode.md
Labels: v1.0

#342 2021-10-20 the airnode doc
  docs/airnode/pre-alpha/README.md
  docs/airnode/pre-alpha/assets/diagrams/summary-airnode-2-parts.drawio
  docs/airnode/pre-alpha/assets/images/summary-airnode-2-parts.png
  docs/airnode/v1.0/README.md
  docs/airnode/v1.0/assets/diagrams/summary-airnode-2-parts.drawio
  docs/airnode/v1.0/assets/images/summary-airnode-2-parts.png
  docs/common/the-airnode.md
Labels: v1.0

#373 AN-133 component to pull the config
  archived/airnode/next/config-json.md
  docs/.vuepress/components/RepoCode.vue
  docs/airnode/v0.2/reference/examples/config-json.md
  docs/airnode/v0.2/reference/examples/secrets-env.md
Labels: v0.2

#375 20211029 broken links package name changes
  docs/.vuepress/config.js
  docs/airnode/pre-alpha/guides/provider/api-integration.md
  docs/airnode/v0.2/concepts/README.md
  docs/airnode/v0.2/concepts/requester.md
  docs/airnode/v0.2/grp-developers/call-an-airnode.md
  docs/airnode/v0.2/grp-developers/guides/smart-contracts-platform/self-serve-integration.md
  docs/airnode/v0.2/grp-developers/self-serve-platforms.md
  docs/airnode/v0.2/grp-developers/using-templates.md
  docs/airnode/v0.2/grp-providers/docker/client-image.md
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.2/grp-providers/tutorial/README.md
  docs/airnode/v0.2/reference/examples/config-json.md
  docs/airnode/v0.2/reference/examples/config-local.json
  docs/airnode/v0.2/reference/examples/config-provider.json
  docs/airnode/v0.2/reference/packages/README.md
  docs/airnode/v0.2/reference/packages/admin-cli-commands.md
  docs/airnode/v0.2/reference/specifications/airnode-abi-specifications.md
  docs/airnode/v0.2/reference/templates/ois-json.md
  package.json
  update-files.cmd
  update-files.sh
Labels: v0.2

#374 Cache yarn dependencies in check-format workflow
  .github/workflows/check-format.yaml
Labels: enhancement, v0.2

#376 AN-236 Update contract addresses
  docs/airnode/v0.2/reference/airnode-addresses.md
Labels: v0.2

#378 AN-303 release v0.2
  .vscode/settings.json
  docs/.vuepress/blog-posts.json
  docs/.vuepress/config.js
  docs/.vuepress/redirects
  docs/dev/assets/img/version-picklist2.png
  docs/dev/deployment.md
  docs/dev/lychee.md
  docs/dev/plugins.md
  docs/dev/quirks.md
  docs/dev/sidebar.js
  docs/dev/versioning.md
  docs/dev/vuepress-server.md
  package.json
  update-files.cmd
  update-files.sh
  yarn.lock
Labels: v0.2

#379 Validator md was not ready in time for v.0.0 init release
  docs/airnode/v0.2/sidebar.js
Labels: v0.2

#377 Check for airnode config changes using Actions
  .github/workflows/scheduled_config_pr.yaml
Labels: v0.2

#380 Embarrasing grammar in the first paragragh.
  docs/airnode/v0.2/README.md
Labels: v0.2
