Repository api3dao/api3-docs, pull requests merged in 2021-09, with the labels that each got.

#187 AN-178: Return dummy chain metadata on pre-alpha instead of leaving i…
  docs/pre-alpha/airnode/specifications/reserved-parameters.md
Labels: documentation, pre-alpha

#184 Add redirects for API Readme links
  docs/.vuepress/redirects
Labels: enhancement

#242 AN-114: Extend the admin package to interact with AirnodeRequesterRrp…
  docs/airnode/next/concepts/authorizer.md
  docs/airnode/next/reference/cli-commands.md
Labels: documentation, v0.1.0

#243 AN-120: Document adminnable contracts
  docs/airnode/next/concepts/adminnable.md
Labels: documentation, v0.1.0

#245 Fixed a little mess from a merge conflict
  docs/airnode/next/concepts/authorizer.md
Labels: v0.1.0

#248 An 202
  docs/airnode/next/assets/diagrams/concepts-sponsor-relationships.drawio
  docs/airnode/next/assets/images/concepts-sponsor-relationships.png
  docs/airnode/next/concepts/sponsor.md
  docs/airnode/next/reference/cli-commands.md
Labels: v0.1.0

#249 AN-202 Work on Admin CLI commands
  docs/.vuepress/components/ChainsSupported.vue
  docs/.vuepress/components/Divider.vue
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-authorizers-notes.md
  docs/airnode/next/reference/airnode-addresses.md
  docs/airnode/next/reference/cli-commands.md
  docs/airnode/next/sidebar.js
Labels: v0.1.0

#251 AN-198-2021-09-28
  docs/airnode/next/assets/diagrams/concepts-authorizers.drawio
  docs/airnode/next/assets/diagrams/concepts-relay-metadata.drawio
  docs/airnode/next/assets/images/concepts-authorizers.png
  docs/airnode/next/assets/images/concepts-relay-metadata.png
  docs/airnode/next/concepts/authorizer.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-authorizers.md
  docs/airnode/next/reference/cli-commands.md
  docs/airnode/next/reference/deployment-files/config-json.md
Labels: v0.1.0

#252 Changed authorizer.md > authorization.md
  docs/airnode/next/concepts/adminnable.md
  docs/airnode/next/concepts/airnode.md
  docs/airnode/next/concepts/authorization.md
  docs/airnode/next/concepts/endpoint.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-authorizers.md
  docs/airnode/next/reference/cli-commands.md
  docs/airnode/next/reference/deployment-files/config-json.md
  docs/airnode/next/sidebar.js
Labels: v0.1.0

#254 AN-239 related apply auth
  docs/airnode/next/concepts/authorization.md
  docs/airnode/next/grp-developers/call-an-airnode.md
  docs/airnode/next/grp-developers/self-serve-platforms.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-auth-notes.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-auth.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/apply-authorizers.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/next/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/next/reference/airnode-addresses.md
  docs/airnode/next/reference/specifications/reserved-parameters.md
  docs/airnode/next/sidebar.js
Labels: v0.1.0

#253 Specify contract for dashboard attribute updates
  docs/dao-members/contract-architecture/dashboard-attributes.md
  docs/dao-members/contract-architecture/pool.md
Labels: v0.1.0

#255 AN-244_2021-09-29
  docs/airnode/next/concepts/airnode-auth.md
  docs/airnode/next/concepts/api-auth.md
  docs/airnode/next/sidebar.js
Labels: v0.1.0

#256 AN-242 Change command to derive-sponsor-wallet-address
  docs/airnode/next/concepts/sponsor.md
  docs/airnode/next/grp-developers/requesters-sponsors.md
  docs/airnode/next/reference/cli-commands.md
Labels: v0.1.0

#257 AN-242 Missed one command to change for derive-sponsor-wallet-address
  docs/airnode/next/grp-developers/requesters-sponsors.md
Labels: v0.1.0

#258 Changed command output displays
  docs/airnode/next/grp-developers/requesters-sponsors.md
Labels: v0.1.0

#259 Added isAuthorizer to diagram
  docs/airnode/next/assets/diagrams/concepts-authorizers.drawio
  docs/airnode/next/assets/images/concepts-authorizers.png
Labels: v0.1.0

#260 AN-240 2021-09-30
  docs/.vuepress/components/Caption.vue
  docs/.vuepress/components/ChainsSupported.vue
  docs/.vuepress/components/Todo.vue
  docs/airnode/next/grp-developers/using-templates.md
Labels: v0.1.0

#261 Wrap deployer command sample path with quotes
  docs/airnode/next/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/next/grp-providers/using-docker.md
  docs/airnode/pre-alpha/guides/docker/client-image.md
  docs/airnode/pre-alpha/guides/docker/deployer-image.md
  docs/airnode/pre-alpha/guides/provider/deploying-airnode.md
Labels: v0.1.0

#263 AN-232_2021-09-30
  docs/airnode/pre-alpha/airnode/specifications/reserved-parameters.md
  docs/dev/link-validator.md
  link-validator.js
Labels: v0.1.0

#262 AN-121: Document authorizer contracts
  docs/airnode/next/concepts/authorization.md
Labels: documentation, v0.1.0
