Repository api3dao/api3-docs, pull requests merged in 2021-12, with the labels that each got.

#447 AN-385.1 security schemes
  docs/.vuepress/blog-posts.json
  docs/airnode/v0.3/assets/diagrams/security-schemes.drawio
  docs/airnode/v0.3/assets/images/security-schemes.png
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/apply-auth.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.3/reference/specifications/reserved-parameters.md
  docs/airnode/v0.3/sidebar.js
Labels: v0.3

#448 AN-420.1 gcp issues
  docs/.vuepress/enhanceApp.js
  docs/airnode/v0.3/assets/diagrams/api-provider-overview-aws.drawio
  docs/airnode/v0.3/assets/diagrams/api-provider-overview-container.drawio
  docs/airnode/v0.3/assets/diagrams/api-provider-overview-gcp.drawio
  docs/airnode/v0.3/assets/diagrams/api-provider-overview.drawio
  docs/airnode/v0.3/assets/images/api-provider-overview-aws.png
  docs/airnode/v0.3/assets/images/api-provider-overview-container.png
  docs/airnode/v0.3/assets/images/api-provider-overview-gcp.png
  docs/airnode/v0.3/assets/images/api-provider-overview.png
  docs/airnode/v0.3/grp-providers/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: v0.3

#449 AN-420-item-6 - /airnode/v0.3/README adjusted to include GCP
  docs/airnode/v0.3/README.md
  docs/airnode/v0.3/assets/diagrams/summary-airnode-2-parts.drawio
  docs/airnode/v0.3/assets/images/summary-airnode-2-parts.png
Labels: v0.3

#451 AN-420 items 4 5
  docs/airnode/v0.3/reference/deployment-files/README.md
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.3/reference/deployment-files/secrets-env.md
  docs/airnode/v0.3/reference/examples/config-cloud.json
  docs/airnode/v0.3/reference/examples/config-json.md
  docs/airnode/v0.3/reference/examples/secrets-env.md
  docs/airnode/v0.3/reference/templates/config-json.md
  docs/airnode/v0.3/reference/templates/secrets-env.md
Labels: v0.3

#452 AN-420 item 3 HTTP Gateway
  docs/airnode/v0.3/assets/diagrams/gateway.drawio
  docs/airnode/v0.3/assets/images/gateway.png
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/http-gateway.md
Labels: v0.3

#453 AN-420-item-2
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: v0.3

#456 AN412 prep for v0.3 deployment
  docs/.vuepress/config.js
  docs/.vuepress/redirects
  docs/airnode/v0.3/concepts/README.md
  docs/airnode/v0.3/concepts/authorization.md
  docs/airnode/v0.3/concepts/requester.md
  docs/airnode/v0.3/grp-developers/call-an-airnode.md
  docs/airnode/v0.3/grp-developers/self-serve-platforms.md
  docs/airnode/v0.3/grp-developers/using-templates.md
  docs/airnode/v0.3/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.3/grp-providers/docker/client-image.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/tutorial/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/reference/packages/README.md
  docs/airnode/v0.3/reference/packages/adapter.md
  docs/airnode/v0.3/reference/packages/admin-cli.md
  docs/airnode/v0.3/reference/packages/airnode-abi.md
  docs/airnode/v0.3/reference/packages/deployer.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.3/reference/specifications/airnode-abi-specifications.md
  docs/airnode/v0.3/reference/templates/ois-json.md
  package.json
Labels: v0.3

#455 Document skip-version-check deployer option
  docs/airnode/v0.3/reference/packages/deployer.md
Labels: v0.3

#459 AN415.1 dynamic redirect
  docs/.vuepress/config.js
  docs/.vuepress/enhanceApp.js
  docs/dev/plugins.md
  docs/dev/redirects.md
  docs/dev/sidebar.js
Labels: v0.3

#460 Skip fake url in CI
  .github/workflows/lychee.toml
Labels: bug, v0.3

#461 AN-420 item 12 win syntax
  docs/.vuepress/components/DeleteAirnodeAws.vue
  docs/.vuepress/enhanceApp.js
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: enhancement, v0.3

#462 20211206-corrections
  docs/airnode/v0.2/concepts/chain-providers.md
  docs/airnode/v0.3/concepts/chain-providers.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
Labels: bug, v0.3

#463 Chain provider changes
  docs/airnode/v0.2/concepts/chain-providers.md
Labels: bug, v0.3

#464 AN420 #8 Update the image for configure-airnode.md to include gcloud.
  docs/airnode/v0.3/assets/diagrams/config-json.drawio
  docs/airnode/v0.3/assets/images/config-json.png
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
Labels: enhancement, v0.3

#465 The guide no longer treats GCP as a second class citizen.
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/README.md
Labels: enhancement, v0.3

#466 An414.1
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-integration.md
  docs/dev/deployment.md
  docs/dev/link-validator.md
  docs/dev/plugins.md
  libs/link-validator.js
  libs/monorepo-readmes
  package.json
Labels: v0.3

#467 Change 0.3.0 code examples to use 0.3.1
  docs/airnode/v0.3/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.3/grp-providers/docker/client-image.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/src/config.json
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-container/src/config.json
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/src/config.json
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.3/reference/deployment-files/receipt-json.md
  docs/airnode/v0.3/reference/examples/config-cloud.json
  docs/airnode/v0.3/reference/examples/config-local.json
  docs/airnode/v0.3/reference/packages/admin-cli.md
  docs/airnode/v0.3/reference/templates/config-json.md
Labels: v0.3

#468 2021207.1 corrections
  docs/.vuepress/redirects
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.3/reference/examples/config-cloud.json
  docs/airnode/v0.3/reference/examples/config-local.json
Labels: v0.3

#469 20211207.2 docker image latest bump
  docs/.vuepress/components/DockerImageVersions.vue
  docs/dev/deployment.md
  docs/dev/versioning.md
Labels: v0.3

#470 Attempt to fix the /latest route
  docs/.vuepress/enhanceApp.js
Labels: bug

#471 20211208.1 latest redirects
  docs/.vuepress/components/LatestRedirects.vue
  docs/.vuepress/enhanceApp.js
  docs/.vuepress/redirects
  docs/dev/redirects.md
  libs/link-validator.js
Labels: bug, v0.3

#472 20211208 corrections
  docs/airnode/v0.2/grp-developers/using-templates.md
  docs/airnode/v0.3/assets/diagrams/sponsor-overview.drawio
  docs/airnode/v0.3/assets/images/sponsor-overview.png
  docs/airnode/v0.3/concepts/sponsor.md
  docs/airnode/v0.3/grp-developers/call-an-airnode.md
  docs/airnode/v0.3/grp-developers/requesters-sponsors.md
  docs/airnode/v0.3/grp-developers/using-templates.md
Labels: corrections, v0.3

#473 More clarity on sponsors and requesters.
  docs/airnode/v0.3/assets/diagrams/sponsor-overview.drawio
  docs/airnode/v0.3/assets/images/sponsor-overview.png
  docs/airnode/v0.3/concepts/sponsor.md
  docs/airnode/v0.3/grp-developers/requesters-sponsors.md
Labels: corrections, v0.3

#475 20211210.1 corrections
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp.zip
  docs/airnode/pre-alpha/airnode/specifications/config-json.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/aws-env.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/config-json.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/secrets-env.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/aws.env
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/secrets.env
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/config-json.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/secrets-env.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/secrets.env
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/config-json.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/secrets-env.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/secrets.env
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/dev/versioning.md
  docs/dev/zip-files.md
  libs/zip-files.js
Labels: corrections, v0.3, v0.4

#476 Update CI to test v0.3, skip v0.4, fix html urls
  .github/workflows/check-links-imgs.yaml
  .github/workflows/lychee.toml
  docs/airnode/v0.3/concepts/authorization.md
  docs/airnode/v0.3/grp-developers/call-an-airnode.md
  docs/airnode/v0.3/grp-developers/requesters-sponsors.md
  docs/airnode/v0.3/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.3/reference/packages/adapter.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.3/reference/specifications/reserved-parameters.md
Labels: v0.3

#478 AN-404.1 document sets
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/components/Sidebar.vue
  docs/.vuepress/components/SubSites.vue
  docs/.vuepress/components/Versions.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/img/arrow-down-16.png
  docs/.vuepress/public/img/arrow-right-16.png
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/sidebar.js
  docs/dev/common-directory.md
  docs/dev/custom-components.md
  docs/dev/deployment.md
  docs/dev/override-components.md
  docs/dev/theme.md
  docs/dev/versioning.md
  docs/ois/v1.0.0/README.md
  docs/ois/v1.0.0/sidebar.js
Labels: v0.4

#479 2021 12 14.1 corrections
  docs/.vuepress/styles/index.styl
  docs/airnode/v0.2/grp-developers/call-an-airnode.md
  docs/airnode/v0.3/grp-developers/call-an-airnode.md
  docs/airnode/v0.4/concepts/authorization.md
  docs/airnode/v0.4/grp-developers/call-an-airnode.md
  docs/airnode/v0.4/grp-developers/requesters-sponsors.md
  docs/airnode/v0.4/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.4/reference/packages/adapter.md
  docs/airnode/v0.4/reference/packages/validator.md
  docs/airnode/v0.4/reference/specifications/reserved-parameters.md
  docs/dev/override-components.md
Labels: v0.2, pre-alpha, v0.3, v0.4

#482 Added use of templates for convertor command
  docs/airnode/v0.4/reference/packages/validator.md
Labels: v0.4

#483 An448 buttons landing page
  docs/.vuepress/components/DocumentSetButtons.vue
  docs/.vuepress/components/Navbar.vue
  docs/README.md
Labels: v0.4

#485 Hide the hamburger menu for landing page
  docs/.vuepress/components/Navbar.vue
Labels: v0.4

#486 Decision was not to include the convertor templates.
  docs/airnode/v0.4/reference/packages/validator.md
Labels: v0.4

#484 Document the EIP-1559 configuration extension to Airnode
  docs/airnode/v0.4/concepts/chain-providers.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/examples/config-cloud.json
  docs/airnode/v0.4/reference/examples/config-local.json
Labels: v0.4

#488 Smaller icons
  docs/.vuepress/components/DocumentSets.vue
Labels: v0.4

#489 20211217.1 corrections
  docs/.vuepress/components/DocumentSets.vue
  docs/airnode/v0.4/concepts/airnode-auth.md
  docs/airnode/v0.4/reference/specifications/ois.md
Labels: v0.4

#490 SDK now supports versioned templates
  docs/airnode/v0.4/reference/packages/validator.md
Labels: v0.4

#491 Added link to the validator package templates folder in hte monrepo.
  docs/airnode/v0.4/reference/packages/validator.md
Labels: corrections, enhancement, v0.4

#492 GitHub issue 480, Derivation Path incorrect.
  docs/airnode/v0.2/concepts/sponsor.md
  docs/airnode/v0.3/concepts/sponsor.md
  docs/airnode/v0.4/concepts/sponsor.md
Labels: corrections, v0.2, v0.3, v0.4

#493 2021-12-20 GH439 landing page remove menu space
  .vscode/settings.json
  docs/.vuepress/components/Navbar.vue
Labels: v0.4

#494 BEC73.1 Beacon intro docs
  docs/.vuepress/components/BeaconWarning.vue
  docs/.vuepress/components/DocumentSets.vue
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/assets/diagrams/dapp-beacon-airnode.drawio
  docs/beacon/v0.1/assets/diagrams/dapp-beacon.drawio
  docs/beacon/v0.1/assets/images/dapp-beacon-airnode.png
  docs/beacon/v0.1/assets/images/dapp-beacon.png
  docs/beacon/v0.1/create-a-beacon/README.md
  docs/beacon/v0.1/sidebar.js
  docs/beacon/v0.1/using-a-beacon/README.md
  docs/beacon/v0.1/why-use-beacons.md
Labels: corrections, enhancement, v0.4

#495 Console output removed
  docs/.vuepress/components/DocumentSets.vue
Labels: corrections, v0.4

#497 Bec73.2 requester call example
  .vscode/settings.json
  docs/.vuepress/components/BeaconWarning.vue
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/public/img/airnode-inactive.png
  docs/.vuepress/public/img/api3-inactive.png
  docs/.vuepress/public/img/beacon-active.png
  docs/.vuepress/public/img/beacon-inactive.png
  docs/.vuepress/public/img/dao-inactive.png
  docs/.vuepress/public/img/ois-active.png
  docs/.vuepress/public/img/ois-inactive.png
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/assets/diagrams/beacon-airnode.drawio
  docs/beacon/v0.1/assets/diagrams/dapp-beacon-airnode.drawio
  docs/beacon/v0.1/assets/diagrams/dapp-beacon.drawio
  docs/beacon/v0.1/assets/images/beacon-airnode.png
  docs/beacon/v0.1/assets/images/dapp-beacon-airnode.png
  docs/beacon/v0.1/assets/images/dapp-beacon.png
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/introduction/why-use-beacons.md
  docs/beacon/v0.1/refresh-a-beacon.md
  docs/beacon/v0.1/sidebar.js
  docs/beacon/v0.1/using-a-beacon/README.md
  docs/beacon/v0.1/why-use-beacons.md
Labels: v0.4

#500 BEC73.3-functions
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/public/img/Beacons-icon-black.png
  docs/.vuepress/public/img/Beacons-icon-green.png
  docs/.vuepress/public/img/Beacons-icon-white.png
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/assets/diagrams/beacon-airnode.drawio
  docs/beacon/v0.1/assets/diagrams/dapp-beacon.drawio
  docs/beacon/v0.1/assets/images/beacon-airnode.png
  docs/beacon/v0.1/assets/images/dapp-beacon.png
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/functions/reader-can-read-beacon.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/beacon/v0.1/sidebar.js
Labels: enhancement, v0.4

#503 2021_12_29_corrections
  docs/.vuepress/blog-posts.json
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/redirects
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/beacon/v0.1/introduction/why-use-beacons.md
  docs/beacon/v0.1/refresh-a-beacon.md
Labels: v0.4

#505 Wrong object name to call airnodeRrp.makeFullRequest()
  docs/airnode/v0.2/grp-developers/call-an-airnode.md
  docs/airnode/v0.3/grp-developers/call-an-airnode.md
  docs/airnode/v0.4/grp-developers/call-an-airnode.md
Labels: corrections

#506 AN460_Added back options chain fields missing since pre-alpha.
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/examples/config-cloud.json
  docs/airnode/v0.4/reference/examples/config-local.json
  docs/airnode/v0.4/reference/templates/config-json.md
Labels: corrections, v0.4

#507 AN460.2_chain_fields_missing_v0.2_v0.3
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.2/reference/deployment-files/config-json.md
  docs/airnode/v0.2/reference/examples/config-local.json
  docs/airnode/v0.2/reference/examples/config-provider.json
  docs/airnode/v0.2/reference/templates/config-json.md
  docs/airnode/v0.2/sidebar.js
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.3/reference/examples/config-cloud.json
  docs/airnode/v0.3/reference/examples/config-local.json
  docs/airnode/v0.3/reference/templates/config-json.md
Labels: corrections, v0.2, v0.3

#508 AN460.3 Code sample missing chain fields.
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
Labels: corrections, v0.2, v0.3, v0.4

#509 BEC73.4 general cleanup
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/public/img/Beacons-active.png
  docs/.vuepress/public/img/Beacons-default.png
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/assets/diagrams/beacon-airnode.drawio
  docs/beacon/v0.1/assets/diagrams/dapi-beacons.drawio
  docs/beacon/v0.1/assets/diagrams/dapp-beacon.drawio
  docs/beacon/v0.1/assets/images/beacon-airnode.png
  docs/beacon/v0.1/assets/images/dapi-beacons.png
  docs/beacon/v0.1/assets/images/dapp-beacon.png
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/functions/reader-can-read-beacon.md
  docs/beacon/v0.1/functions/request-beacon-update.md
Labels: corrections, v0.4

#510 Forget to set the icon in the code block for temp prod use.
  docs/.vuepress/components/DocumentSets.vue
Labels: corrections, v0.4

#512 Removed the TOC
  docs/beacon/v0.1/introduction/why-use-beacons.md
Labels: corrections, v0.4

#513 minConfirmations commented out for v0.2+
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.2/reference/deployment-files/config-json.md
  docs/airnode/v0.2/reference/examples/config-local.json
  docs/airnode/v0.2/reference/examples/config-provider.json
  docs/airnode/v0.2/reference/templates/config-json.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.3/reference/examples/config-cloud.json
  docs/airnode/v0.3/reference/examples/config-local.json
  docs/airnode/v0.3/reference/templates/config-json.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/examples/config-cloud.json
  docs/airnode/v0.4/reference/examples/config-local.json
  docs/airnode/v0.4/reference/templates/config-json.md
Labels: corrections, v0.2, v0.3, v0.4

#514 Core technical team Dec report
  docs/.vuepress/blog-posts.json
Labels: enhancement

#515 Moved the validator monoerepo build back to its README.
  docs/airnode/v0.4/reference/packages/validator.md
Labels: enhancement, v0.4
