Repository api3dao/api3-docs, pull requests merged in 2022-06, with the labels that each got.

#785 Moving the Data Feed docs forward based on data-feed-reader-example
  docs/data-feeds/README.md
  docs/data-feeds/developers/README.md
  docs/data-feeds/developers/read-data-feed-value-with-dapi-name.md
  docs/data-feeds/developers/read-data-feed-value-with-id.md
  docs/data-feeds/developers/read-data-feed-with-dapi-name.md
  docs/data-feeds/developers/read-data-feed-with-id.md
  docs/data-feeds/introduction/why-use-data-feeds.md
  docs/data-feeds/sidebar.js
Labels: enhancement

#787 Content reflective of data-feed-reader-example
  docs/data-feeds/developers/README.md
  docs/data-feeds/developers/data-feed-id-to-reader-to-whitelist-status.md
  docs/data-feeds/developers/read-data-feed-value-with-dapi-name.md
  docs/data-feeds/developers/read-data-feed-value-with-id.md
  docs/data-feeds/developers/read-data-feed-with-dapi-name.md
  docs/data-feeds/developers/read-data-feed-with-id.md
  docs/data-feeds/developers/reader-can-read-datafeed.md
Labels: enhancement

#788 Clean use of IDs and dAPI names terminology, data feeds
  docs/data-feeds/developers/data-feed-id-to-reader-to-whitelist-status.md
  docs/data-feeds/developers/read-data-feed-value-with-dapi-name.md
  docs/data-feeds/developers/read-data-feed-value-with-id.md
  docs/data-feeds/developers/read-data-feed-with-dapi-name.md
  docs/data-feeds/developers/read-data-feed-with-id.md
  docs/data-feeds/developers/reader-can-read-datafeed.md
Labels: corrections, enhancement

#792 First pass at the change to dAPI primary focus
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/config.js
  docs/dapis/README.md
  docs/dapis/assets/diagrams/.$dapi-beacons.drawio.bkp
  docs/dapis/assets/diagrams/.$dapp-beacon.drawio.bkp
  docs/dapis/assets/diagrams/.$why-power-beacons.drawio.bkp
  docs/dapis/assets/diagrams/beacon-airnode.drawio
  docs/dapis/assets/diagrams/dapi-beacons.drawio
  docs/dapis/assets/diagrams/dapp-beacon.drawio
  docs/dapis/assets/diagrams/why-power-beacons.drawio
  docs/dapis/assets/images/beacon-airnode.png
  docs/dapis/assets/images/dapi-beacons.png
  docs/dapis/assets/images/dapp-beacon.png
  docs/dapis/assets/images/monitor.png
  docs/dapis/assets/images/why-power-beacons.png
  docs/dapis/developers/README.md
  docs/dapis/developers/data-feed-id-to-reader-to-whitelist-status.md
  docs/dapis/developers/read-data-feed-value-with-dapi-name.md
  docs/dapis/developers/read-data-feed-value-with-id.md
  docs/dapis/developers/read-data-feed-with-dapi-name.md
  docs/dapis/developers/read-data-feed-with-id.md
  docs/dapis/developers/reader-can-read-datafeed.md
  docs/dapis/documentation.json
  docs/dapis/introduction/why-power.md
  docs/dapis/introduction/why-use-dapis.md
  docs/dapis/reference/amberdata.json
  docs/dapis/reference/beacon-browser.md
  docs/dapis/reference/beacon-scheme.md
  docs/dapis/reference/chains.md
  docs/dapis/reference/monitor.md
  docs/dapis/sidebar.js
  docs/data-feeds/assets/diagrams/.$beacon-airnode.drawio.bkp
  docs/data-feeds/assets/diagrams/.$dapi-beacons.drawio.bkp
  docs/data-feeds/assets/diagrams/.$dapp-beacon.drawio.bkp
  docs/data-feeds/assets/diagrams/dapi-beacons.drawio
  docs/data-feeds/assets/diagrams/dapp-beacon.drawio
  docs/data-feeds/assets/diagrams/why-power-beacons.drawio
  docs/data-feeds/assets/images/dapi-beacons.png
  docs/data-feeds/assets/images/dapp-beacon.png
  docs/data-feeds/assets/images/why-power-beacons.png
  docs/data-feeds/introduction/why-use-data-feeds.md
  docs/data-feeds/reference/chains.md
Labels: corrections

#795 Bec186 20220606
  docs/dapis/README.md
  docs/dapis/assets/diagrams/.$dapi-beacons.drawio.bkp
  docs/dapis/assets/diagrams/.$dapi-beacons.drawio.dtmp
  docs/dapis/assets/diagrams/dapi-beacons.drawio
  docs/dapis/assets/images/dapi-beacons.png
  docs/dapis/developers/README.md
  docs/dapis/developers/data-feed-id-to-reader-to-whitelist-status.md
  docs/dapis/developers/read-data-feed-value-with-dapi-name.md
  docs/dapis/developers/read-data-feed-value-with-id.md
  docs/dapis/developers/read-data-feed-with-dapi-name.md
  docs/dapis/developers/read-data-feed-with-id.md
  docs/dapis/developers/reader-can-read-datafeed.md
  docs/dapis/introduction/why-power.md
  docs/dapis/introduction/why-use-dapis.md
  docs/dapis/reference/beacon-scheme.md
  docs/dapis/reference/schemes.md
  docs/dapis/sidebar.js
Labels: enhancement

#797 Bec493 dapi list
  .vscode/settings.json
  docs/.vuepress/components/dapis/browsers/DapiList.vue
  docs/dapis/developers/README.md
  docs/dapis/reference/dapi-browser.md
  docs/dapis/sidebar.js
Labels: enhancement

#796 Add create-inline-template documentation
  docs/airnode/v0.7/reference/packages/admin-cli.md
Labels: enhancement, v0.7

#799 Start some layout ideas
  docs/chainapi/how-to-guide/README.md
  docs/chainapi/how-to-guide/deployments.md
  docs/chainapi/how-to-guide/integrations.md
  docs/chainapi/more/more-stuff.md
  docs/chainapi/reference/README.md
  docs/chainapi/sidebar.js
Labels: ChainAPI

#800 Several corrections , Airnode and dAPIs doc sets
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.6/grp-providers/docker/deployer-image.md
  docs/airnode/v0.6/reference/deployment-files/config-json.md
  docs/airnode/v0.7/grp-providers/docker/deployer-image.md
  docs/airnode/v0.7/reference/deployment-files/config-json.md
  docs/dapis/developers/README.md
  docs/dapis/developers/data-feed-id-to-reader-to-whitelist-status.md
  docs/dapis/developers/read-data-feed-value-with-dapi-name.md
  docs/dapis/developers/read-data-feed-value-with-id.md
  docs/dapis/developers/read-data-feed-with-dapi-name.md
  docs/dapis/developers/read-data-feed-with-id.md
  docs/dapis/developers/reader-can-read-datafeed.md
  docs/dapis/introduction/why-use-dapis.md
Labels: corrections

#802 Add network picklist to dAPI browser
  .vscode/settings.json
  docs/.vuepress/components/dapis/browsers/DapiList.vue
  docs/dapis/reference/dapi-browser.md
Labels: enhancement, dAPIs

#803 20220609 corrections
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.6/grp-providers/docker/deployer-image.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.6/reference/deployment-files/config-json.md
  docs/airnode/v0.7/grp-providers/docker/deployer-image.md
  docs/airnode/v0.7/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/v0.7/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/beacon/v0.1/reference/beacon-ids.md
  docs/dapis/reference/monitor.md
Labels: corrections

#808 dAPI values and source Beacons list
  docs/.vuepress/components/dapis/browsers/DapiDetails.vue
  docs/.vuepress/components/dapis/browsers/DapiList.vue
  docs/.vuepress/components/dapis/browsers/DapiValue.vue
  docs/dapis/reference/dapi-browser.md
Labels: enhancement

#812 20220613 airnode 0.6.5
  docs/.vuepress/components/DockerImageVersions.vue
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.6.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.6.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.6.zip
  docs/airnode/v0.6/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.6/grp-providers/docker/client-image.md
  docs/airnode/v0.6/grp-providers/docker/deployer-image.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.6/reference/deployment-files/config-json.md
  docs/airnode/v0.6/reference/deployment-files/receipt-json.md
  docs/airnode/v0.6/reference/examples/config-cloud.json
  docs/airnode/v0.6/reference/examples/config-local.json
  docs/airnode/v0.6/reference/packages/admin-cli.md
  docs/airnode/v0.6/reference/templates/config-json.md
Labels: enhancement, v0.6

#813 Bec493.3 dapi browser
  docs/.vuepress/components/dapis/browsers/DapiDetails.vue
  docs/.vuepress/components/dapis/browsers/DapiList.vue
  docs/.vuepress/components/dapis/browsers/DapiValue.vue
Labels: enhancement, dAPIs

#814 Adjust heading 2 "References"
  docs/airnode/v0.7/grp-providers/guides/build-an-airnode/configuring-airnode.md
Labels: enhancement, v0.7

#815 20220604 dapi board items
  docs/.vuepress/components/dapis/browsers/DapiValue.vue
  docs/dapis/developers/README.md
  docs/dapis/developers/data-feed-id-to-reader-to-whitelist-status.md
  docs/dapis/developers/read-data-feed-value-with-dapi-name.md
  docs/dapis/developers/read-data-feed-value-with-id.md
  docs/dapis/developers/read-data-feed-with-dapi-name.md
  docs/dapis/developers/read-data-feed-with-id.md
  docs/dapis/developers/reader-can-read-datafeed.md
  docs/dapis/introduction/why-use-dapis.md
Labels: corrections, enhancement, dAPIs

#816 Use proper network names
  docs/.vuepress/components/beacons/chains/ChainsItem.vue
  docs/dapis/developers/README.md
Labels: corrections, dAPIs

#817 20220615 general enhancements
  docs/.vuepress/components/dapis/browsers/DapiList.vue
  docs/.vuepress/components/dapis/chains/ChainsItem.vue
  docs/.vuepress/components/dapis/chains/ChainsList.vue
  docs/dapis/README.md
  docs/dapis/assets/diagrams/.$dapi-beacons.drawio.bkp
  docs/dapis/assets/diagrams/.$dapi-beacons.drawio.dtmp
  docs/dapis/assets/diagrams/.$dapp-beacon.drawio.bkp
  docs/dapis/assets/diagrams/.$dapp-beacon.drawio.dtmp
  docs/dapis/assets/diagrams/dapi-beacons.drawio
  docs/dapis/assets/diagrams/dapp-beacon.drawio
  docs/dapis/assets/images/dapp-beacon.png
  docs/dapis/developers/README.md
  docs/dapis/reference/chains.md
  docs/dapis/reference/monitor.md
  docs/dev/quirks.md
Labels: enhancement

#818 Remove Grafana charts
  archived/dapis/beacon-browser.md
  archived/dapis/monitor.md
  docs/dapis/developers/README.md
  docs/dapis/reference/chains.md
  docs/dapis/sidebar.js
Labels: corrections, dAPIs

#819 Template sometimes loads after value
  docs/.vuepress/components/dapis/browsers/DapiDetails.vue
  docs/.vuepress/components/dapis/browsers/DapiList.vue
  docs/.vuepress/components/dapis/browsers/DapiValue.vue
Labels: corrections, dAPIs

#820 Getting the introduction section organized.
  docs/.vuepress/components/dapis/browsers/DapiValue.vue
  docs/chainapi/README.md
  docs/chainapi/assets/diagrams/.$what-overview.drawio.bkp
  docs/chainapi/assets/diagrams/.$what-overview.drawio.dtmp
  docs/chainapi/assets/diagrams/.$why-overview.drawio.bkp
  docs/chainapi/assets/diagrams/what-overview.drawio
  docs/chainapi/assets/diagrams/why-overview.drawio
  docs/chainapi/assets/images/what-overview.png
  docs/chainapi/assets/images/why-overview.png
  docs/chainapi/introduction/why-use-chainapi.md
  docs/chainapi/sidebar.js
  docs/chainapi/user-guides/README.md
  docs/chainapi/user-guides/deployments.md
  docs/chainapi/user-guides/integrations.md
Labels: ChainAPI

#822 20220618 chainapi signup
  docs/.vuepress/components/DocumentSetButtons.vue
  docs/.vuepress/components/DocumentSets.vue
  docs/chainapi/README.md
  docs/chainapi/assets/images/Login.png
  docs/chainapi/assets/images/choose-wallet.png
  docs/chainapi/assets/images/connect.png
  docs/chainapi/assets/images/deployment-status.png
  docs/chainapi/assets/images/integrate-api.png
  docs/chainapi/assets/images/new-deployment.png
  docs/chainapi/example-files/aws.env
  docs/chainapi/example-files/aws.md
  docs/chainapi/example-files/config.json
  docs/chainapi/example-files/config.md
  docs/chainapi/example-files/secrets.env
  docs/chainapi/example-files/secrets.md
  docs/chainapi/introduction/concepts.md
  docs/chainapi/sidebar.js
  docs/chainapi/user-guides/README.md
  docs/chainapi/user-guides/deployments.md
  docs/chainapi/user-guides/integrations.md
  docs/chainapi/user-guides/signup.md
Labels: ChainAPI

#830 Set Airnode v0.7 as latest
  docs/.vuepress/components/DockerImageVersions.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.7.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.7.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.7.zip
  docs/airnode/v0.7/concepts/README.md
  docs/airnode/v0.7/concepts/requester.md
  docs/airnode/v0.7/grp-developers/call-an-airnode.md
  docs/airnode/v0.7/grp-developers/using-templates.md
  docs/airnode/v0.7/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.7/grp-providers/docker/client-image.md
  docs/airnode/v0.7/grp-providers/docker/deployer-image.md
  docs/airnode/v0.7/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.7/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.7/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.7/grp-providers/tutorial/README.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-aws/aws-env.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-aws/config-json.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-aws/secrets-env.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-container/config-json.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-container/secrets-env.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-gcp/config-json.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-gcp/secrets-env.md
  docs/airnode/v0.7/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.7/reference/deployment-files/config-json.md
  docs/airnode/v0.7/reference/deployment-files/receipt-json.md
  docs/airnode/v0.7/reference/examples/config-cloud.json
  docs/airnode/v0.7/reference/examples/config-json.md
  docs/airnode/v0.7/reference/examples/config-local.json
  docs/airnode/v0.7/reference/packages/README.md
  docs/airnode/v0.7/reference/packages/adapter.md
  docs/airnode/v0.7/reference/packages/admin-cli.md
  docs/airnode/v0.7/reference/packages/airnode-abi.md
  docs/airnode/v0.7/reference/packages/deployer.md
  docs/airnode/v0.7/reference/packages/validator.md
  docs/airnode/v0.7/reference/specifications/airnode-abi-specifications.md
  docs/airnode/v0.7/reference/templates/config-json.md
  docs/chainapi/README.md
  docs/chainapi/introduction/concepts.md
  docs/chainapi/introduction/why-use-chainapi.md
  docs/chainapi/reference/README.md
  docs/chainapi/user-guides/integrations.md
  docs/ois/v1.0.0/README.md
  docs/ois/v1.0.0/ois-template.md
  docs/ois/v1.0.0/ois.md
  docs/ois/v1.0.0/reserved-parameters.md
  docs/qrng/README.md
  docs/qrng/providers.md
  docs/qrng/using-qrng.md
Labels: v0.7

#834 Remove new networks field from component data
  docs/.vuepress/components/airnode/ContractAddresses.vue
Labels: Component

#836 Add link to first occurance of nodeVersion
  .github/workflows/check-links-imgs.yaml
  docs/.vuepress/components/airnode/DockerImageVersions.vue
  docs/airnode/v0.2/grp-providers/docker/README.md
  docs/airnode/v0.3/grp-providers/docker/README.md
  docs/airnode/v0.4/grp-providers/docker/README.md
  docs/airnode/v0.5/grp-providers/docker/README.md
  docs/airnode/v0.6/grp-providers/docker/README.md
  docs/airnode/v0.7/grp-providers/docker/README.md
  docs/airnode/v0.8/grp-providers/docker/README.md
Labels: Component

#846 Change URL to latest airnode
  docs/.vuepress/components/DocumentSets.vue
  docs/dapis/README.md
  docs/dapis/introduction/why-power.md
  docs/dapis/introduction/why-use-dapis.md
Labels: corrections

#859 20220629 chainapi terms
  docs/chainapi/introduction/concepts.md
  docs/chainapi/reference/example-files/aws.env
  docs/chainapi/reference/example-files/aws.md
  docs/chainapi/reference/example-files/config.json
  docs/chainapi/reference/example-files/config.md
  docs/chainapi/reference/example-files/secrets.env
  docs/chainapi/reference/example-files/secrets.md
  docs/chainapi/reference/terms.md
  docs/chainapi/sidebar.js
Labels: ChainAPI
