Repository api3dao/api3-docs, pull requests merged in 2022-02, with the labels that each got.

#579 Code sample corrections found by Cameron
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/README.md
Labels: corrections, v0.4

#580 Added spinner and error message
  docs/.vuepress/components/beacons/BeaconList.vue
  docs/.vuepress/public/img/spinner.gif
Labels: enhancement, v0.4

#582 BeaconIds and SelfServeRrpBeaconServerWhitelister.sol
  .vscode/settings.json
  docs/.vuepress/components/beacons/BeaconItem.vue
  docs/.vuepress/components/beacons/BeaconList.vue
  docs/.vuepress/styles/switcher.styl
  docs/beacon/v0.1/introduction/hackathon.md
  docs/beacon/v0.1/reference/contract-addresses.md
Labels: corrections, enhancement, v0.4

#584 Added mention of the beacon-reader-example repo.
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/introduction/hackathon.md
Labels: v0.4

#587 20220207 correction h3 remove airnode
  docs/.vuepress/public/zip-files/quick-deploy-gcp.zip
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/beacon/v0.1/introduction/hackathon.md
Labels: v0.4

#588 An483 gateway v0.4
  docs/.vuepress/components/airnode/tutorials/TutorialResponse.vue
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.4.zip
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
Labels: v0.4

#589 Small grammar changes
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/tutorial/README.md
Labels: v0.4

#591 20220208 adjustments
  docs/.vuepress/redirects
  docs/ois/v1.0.0/ois.md
Labels: v0.4

#593 20220208 hackathon help
  docs/.vuepress/redirects
  docs/beacon/v0.1/introduction/hackathon.md
Labels: v0.4

#595 v0.4 Airnode doc set release
  .github/workflows/check-links-imgs.yaml
  .vscode/settings.json
  archived/SubSites.vue
  docs/.vuepress/components/DockerImageVersions.vue
  docs/.vuepress/components/LatestRedirects.vue
  docs/.vuepress/components/beacons/beaconInfo.json
  docs/.vuepress/config.js
  docs/.vuepress/redirects
  docs/airnode/v0.4/concepts/README.md
  docs/airnode/v0.4/concepts/requester.md
  docs/airnode/v0.4/grp-developers/call-an-airnode.md
  docs/airnode/v0.4/grp-developers/self-serve-platforms.md
  docs/airnode/v0.4/grp-developers/using-templates.md
  docs/airnode/v0.4/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.4/grp-providers/docker/client-image.md
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.4/grp-providers/tutorial/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.4/reference/examples/config-json.md
  docs/airnode/v0.4/reference/packages/README.md
  docs/airnode/v0.4/reference/packages/adapter.md
  docs/airnode/v0.4/reference/packages/admin-cli.md
  docs/airnode/v0.4/reference/packages/airnode-abi.md
  docs/airnode/v0.4/reference/packages/deployer.md
  docs/airnode/v0.4/reference/packages/validator.md
  docs/airnode/v0.4/reference/specifications/airnode-abi-specifications.md
  docs/dev/versioning.md
Labels: v0.4

#597 An538 remove testable
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.5.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.5.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.5.zip
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/examples/config-cloud.json
  docs/airnode/v0.4/reference/examples/config-local.json
  docs/airnode/v0.4/reference/packages/validator.md
  docs/airnode/v0.4/reference/templates/config-json.md
  docs/airnode/v0.5/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.5/grp-providers/docker/client-image.md
  docs/airnode/v0.5/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/deployment-files/receipt-json.md
  docs/airnode/v0.5/reference/examples/config-cloud.json
  docs/airnode/v0.5/reference/examples/config-local.json
  docs/airnode/v0.5/reference/packages/admin-cli.md
  docs/airnode/v0.5/reference/packages/validator.md
  docs/airnode/v0.5/reference/templates/config-json.md
Labels: v0.4

#600 Config missing triggers[n].http protocol needed by test-api-js script
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.5.zip
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
Labels: v0.4

#604 20220210 redirects blank lines
  docs/.vuepress/redirects
  docs/dev/redirects.md
Labels: v0.4

#607 An539 relay security
  docs/.vuepress/components/InfoBtnBlue.vue
  docs/.vuepress/components/InfoBtnGreen.vue
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/ois/v1.0.0/ois.md
  docs/ois/v1.0.0/reserved-parameters.md
Labels: v0.4

#612 20220211 beacons
  docs/.vuepress/components/beacons/BeaconItem.vue
  docs/.vuepress/components/beacons/BeaconList.vue
  docs/.vuepress/config.js
  docs/.vuepress/styles/switcher.styl
  docs/beacon/v0.1/reference/beacon-scheme.md
  docs/beacon/v0.1/sidebar.js
  package.json
  yarn.lock
Labels: v0.4

#615 20220211 maintenance
  docs/.vuepress/blog-posts.json
  docs/.vuepress/redirects
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/config-json.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/config-json.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/config-json.md
  docs/airnode/v0.5/reference/examples/config-json.md
Labels: v0.4

#616 HTTP Gateway maxConcurrency clean-up
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/examples/config-cloud.json
  docs/airnode/v0.5/reference/examples/config-json.md
  docs/airnode/v0.5/reference/examples/config-local.json
  docs/airnode/v0.5/reference/templates/config-json.md
Labels: v0.5

#619 20220212 change insurance
  docs/api3/README.md
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/introduction/why-use-beacons.md
  docs/dao-members/assets/diagrams/dao-pool-staking-2.drawio
  docs/dao-members/assets/diagrams/dao-pool-staking.drawio
  docs/dao-members/assets/diagrams/dao.drawio
  docs/dao-members/assets/images/dao-pool-staking-2.png
  docs/dao-members/assets/images/dao-pool-staking.png
  docs/dao-members/assets/images/dao.png
  docs/dao-members/contract-architecture/pool.md
  docs/dao-members/dashboard/coverage.md
  docs/dao-members/introduction/api3-dao.md
  docs/dao-members/introduction/dao-pool.md
Labels: enhancement, v0.4

#623 AN540 mobile viewport
  docs/.vuepress/components/DeleteAirnodeAws.vue
  docs/.vuepress/styles/index.styl
  docs/airnode/v0.4/concepts/authorization.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/packages/adapter.md
  docs/airnode/v0.4/reference/packages/admin-cli.md
  docs/airnode/v0.4/reference/packages/deployer.md
  docs/airnode/v0.4/reference/templates/config-json.md
  docs/airnode/v0.5/concepts/authorization.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/packages/adapter.md
  docs/airnode/v0.5/reference/packages/admin-cli.md
  docs/airnode/v0.5/reference/packages/deployer.md
  docs/airnode/v0.5/reference/templates/config-json.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/dao-members/dashboard/proposals.md
  docs/ois/v1.0.0/reserved-parameters.md
Labels: v0.4, v0.5

#624 20220214-corrections
  docs/airnode/v0.5/reference/examples/config-cloud.json
  docs/airnode/v0.5/reference/templates/config-json.md
  docs/beacon/v0.1/introduction/hackathon.md
Labels: v0.5

#625 AN540 mobile videos
  docs/.vuepress/components/Video.vue
  docs/dao-members/dashboard/README.md
  docs/dao-members/dashboard/proposals.md
  docs/dao-members/dashboard/staking.md
  docs/dao-members/dashboard/videos.md
  docs/dao-members/dashboard/voting.md
Labels: v0.4, v0.5

#633 20220217 corrections
  docs/.vuepress/components/beacons/BeaconItem.vue
  docs/.vuepress/components/beacons/BeaconList.vue
  docs/airnode/v0.4/concepts/chain-providers.md
  docs/airnode/v0.5/concepts/chain-providers.md
Labels: corrections, v0.4, v0.5

#634 Fix Quick Deploy AWS Windows request command
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
Labels: corrections, v0.3, v0.4, v0.5

#639 AN422 gcp manual removal
  docs/.vuepress/components/DeleteAirnodeAws.vue
  docs/.vuepress/components/DeleteAirnodeGcp.vue
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: enhancement, v0.4, v0.5

#641 Move to Airnode v0.4.1
  docs/.vuepress/components/DockerImageVersions.vue
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.4.zip
  docs/airnode/v0.4/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.4/grp-providers/docker/client-image.md
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/deployment-files/receipt-json.md
  docs/airnode/v0.4/reference/examples/config-cloud.json
  docs/airnode/v0.4/reference/examples/config-local.json
  docs/airnode/v0.4/reference/packages/admin-cli.md
  docs/airnode/v0.4/reference/templates/config-json.md
Labels: enhancement, v0.4

#644 AN548 http signed triggers
  docs/airnode/v0.5/assets/diagrams/config-json.drawio
  docs/airnode/v0.5/assets/images/config-json.png
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-signed-gateway.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/examples/config-cloud.json
  docs/airnode/v0.5/reference/examples/config-json.md
  docs/airnode/v0.5/reference/examples/config-local.json
  docs/airnode/v0.5/reference/examples/secrets-env.md
  docs/airnode/v0.5/reference/templates/aws-env.md
  docs/airnode/v0.5/reference/templates/config-json.md
  docs/airnode/v0.5/reference/templates/secrets-env.md
  docs/airnode/v0.5/sidebar.js
Labels: v0.5

#647 20220224 corrections improvements
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.5.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.5.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.5.zip
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/deployment-files/receipt-json.md
  docs/airnode/v0.5/reference/examples/config-cloud.json
  docs/airnode/v0.5/reference/examples/config-local.json
  docs/airnode/v0.5/reference/packages/admin-cli.md
  libs/monorepo-readmes
Labels: v0.5

#648 AN560 vuepress 1.9.7
  docs/.vuepress/components/Sidebar.vue
  docs/.vuepress/components/api3/JobsEmailAddress.vue
  docs/api3/introduction/work.md
  docs/dao-members/dashboard/staking.md
  package.json
  yarn.lock
Labels: enhancement, v0.4, v0.5
