Repository api3dao/api3-docs, pull requests merged in 2022-10, with the labels that each got.

#1071 20221005 blog posts
  docs/.vuepress/blog-posts.json
  docs/airnode/v0.10/reference/packages/deployer.md
  docs/airnode/v0.10/reference/packages/validator.md
  docs/airnode/v0.3/reference/packages/deployer.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.4/reference/packages/deployer.md
  docs/airnode/v0.4/reference/packages/validator.md
  docs/airnode/v0.5/reference/packages/deployer.md
  docs/airnode/v0.5/reference/packages/validator.md
  docs/airnode/v0.6/reference/packages/deployer.md
  docs/airnode/v0.7/reference/packages/deployer.md
  docs/airnode/v0.7/reference/packages/validator.md
  docs/airnode/v0.8/reference/packages/deployer.md
  docs/airnode/v0.8/reference/packages/validator.md
  docs/airnode/v0.9/reference/packages/deployer.md
  docs/airnode/v0.9/reference/packages/validator.md
Labels: corrections, enhancement

#1072 Prettier formatting needed.
  docs/chainapi/user-guides/Import&Export.md
Labels: corrections, ChainAPI

#1079 Changes for Airnode 0.8.1
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.8.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.8.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.8.zip
  docs/airnode/v0.8/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.8/grp-providers/docker/client-image.md
  docs/airnode/v0.8/grp-providers/docker/deployer-image.md
  docs/airnode/v0.8/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.8/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.8/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config.json
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config.json
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config.json
  docs/airnode/v0.8/reference/deployment-files/config-json.md
  docs/airnode/v0.8/reference/deployment-files/receipt-json.md
  docs/airnode/v0.8/reference/examples/config-cloud.json
  docs/airnode/v0.8/reference/examples/config-local.json
  docs/airnode/v0.8/reference/migration.md
  docs/airnode/v0.8/reference/packages/admin-cli.md
  docs/airnode/v0.8/reference/templates/config-json.md
Labels: v0.8

#1080 Airnode v0.9.0
  docs/.vuepress/components/ois/OisAirnodeVersions.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.9.zip
  docs/airnode/v0.9/concepts/README.md
  docs/airnode/v0.9/concepts/authorizations.md
  docs/airnode/v0.9/concepts/requester.md
  docs/airnode/v0.9/grp-developers/call-an-airnode.md
  docs/airnode/v0.9/grp-developers/using-templates.md
  docs/airnode/v0.9/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.9/grp-providers/docker/client-image.md
  docs/airnode/v0.9/grp-providers/docker/deployer-image.md
  docs/airnode/v0.9/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.9/grp-providers/guides/build-an-airnode/using-authorizations.md
  docs/airnode/v0.9/grp-providers/tutorial/README.md
  docs/airnode/v0.9/grp-providers/tutorial/quick-deploy-aws/aws-env.md
  docs/airnode/v0.9/reference/examples/config-json.md
  docs/airnode/v0.9/reference/packages/README.md
  docs/airnode/v0.9/reference/packages/adapter.md
  docs/airnode/v0.9/reference/packages/admin-cli.md
  docs/airnode/v0.9/reference/packages/airnode-abi.md
  docs/airnode/v0.9/reference/packages/deployer.md
  docs/airnode/v0.9/reference/packages/validator.md
  docs/airnode/v0.9/reference/specifications/airnode-abi-specifications.md
  docs/ois/v1.2/processing.md
Labels: v0.9

#1081 Airnode 0.8.1 must use OIS 1.1.2
  docs/.vuepress/components/ois/OisAirnodeVersions.vue
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.8.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.8.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.8.zip
  docs/airnode/v0.8/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config.json
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config.json
  docs/airnode/v0.8/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config.json
  docs/airnode/v0.8/reference/examples/config-cloud.json
  docs/airnode/v0.8/reference/examples/config-local.json
  docs/airnode/v0.8/reference/migration.md
  docs/airnode/v0.8/reference/packages/README.md
  docs/airnode/v0.8/reference/templates/config-json.md
  docs/airnode/v0.9/reference/migration.md
Labels: corrections, v0.8

#1083 Remove policies from operations readme
  docs/operations/README.md
Labels: corrections

#1084 1047 manual remove buckets
  .vscode/settings.json
  docs/.vuepress/components/airnode/DeleteAirnodeAws.vue
  docs/.vuepress/components/airnode/DeleteAirnodeGcp.vue
  docs/airnode/v0.10/grp-providers/docker/deployer-image.md
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.9/grp-providers/docker/deployer-image.md
  docs/airnode/v0.9/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.9/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: enhancement, v0.9, v0.10

#1078 Chainapi-import&export-updates
  .gitignore
  docs/chainapi/user-guides/Import&Export.md
Labels: ChainAPI

#1091 Grammar issues
  docs/dapis/developers/README.md
Labels: corrections, dAPIs

#1094 Remove: Stable/USD beacon set
  docs/.vuepress/components/dapis/browsers/DapiList.vue
Labels: corrections, dAPIs

#1097 20221019 dapis version references
  docs/.vuepress/config.js
  docs/dapis/developers/README.md
  docs/dapis/introduction/why-use-dapis.md
  docs/dapis/reference/chains.md
  docs/dapis/sidebar.js
Labels: dAPIs

#1099 Added Authorizers to Deployments docs
  docs/chainapi/user-guides/deployments.md
Labels: ChainAPI

#1102 Grammar in the example project reference page
  docs/qrng/reference/qrng-example.md
Labels: corrections, QRNG

#1103 Move supported regions list to cloud-resource.md file
  docs/airnode/v0.10/reference/cloud-resources.md
  docs/airnode/v0.10/reference/deployment-files/config-json.md
  docs/airnode/v0.7/reference/cloud-resources.md
  docs/airnode/v0.7/reference/deployment-files/config-json.md
  docs/airnode/v0.8/reference/cloud-resources.md
  docs/airnode/v0.8/reference/deployment-files/config-json.md
  docs/airnode/v0.9/reference/cloud-resources.md
  docs/airnode/v0.9/reference/deployment-files/config-json.md
Labels: enhancement, v0.7, v0.8, v0.9, v0.10

#1104 Remove the negative, add the positive
  docs/.vuepress/blog-posts.json
  docs/api3/introduction/decentrally-governed-oracle-networks.md
Labels: enhancement

#1105 Remove units from from the column Initial Value
  docs/dao-members/contract-architecture/dashboard-attributes.md
Labels: corrections
