Repository api3dao/api3-docs, pull requests merged in 2022-03, with the labels that each got.

#652 AN581 cli link checking
  .gitignore
  .vscode/settings.json
  README.md
  docs/dev/deployment.md
  docs/dev/link-validator.md
  libs/link-validator-repos.js
  libs/link-validator.js
  libs/monorepo-readmes
  package.json
Labels: enhancement

#656 AN564 enhance relay meta data
  .vscode/settings.json
  docs/airnode/v0.4/assets/diagrams/relay-meta-flow.drawio
  docs/airnode/v0.4/assets/images/relay-meta-flow.png
  docs/airnode/v0.4/concepts/README.md
  docs/airnode/v0.4/concepts/authorization.md
  docs/airnode/v0.4/concepts/relay-meta-auth.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/apply-auth.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.4/sidebar.js
  docs/airnode/v0.5/assets/diagrams/relay-meta-flow.drawio
  docs/airnode/v0.5/assets/images/relay-meta-flow.png
  docs/airnode/v0.5/concepts/README.md
  docs/airnode/v0.5/concepts/authorization.md
  docs/airnode/v0.5/concepts/relay-meta-auth.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/apply-auth.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.5/sidebar.js
  docs/ois/v1.0.0/ois.md
Labels: enhancement, v0.4, v0.5

#657 AN564 corrections and improvements
  docs/airnode/v0.4/assets/diagrams/security-schemes.drawio
  docs/airnode/v0.4/assets/images/security-schemes.png
  docs/airnode/v0.4/concepts/relay-meta-auth.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.5/assets/diagrams/security-schemes.drawio
  docs/airnode/v0.5/assets/images/security-schemes.png
  docs/airnode/v0.5/concepts/relay-meta-auth.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/api-security.md
Labels: corrections, enhancement, v0.4, v0.5

#659 AN-344 hide self-serve-integration docs
  archived/airnode/v0.2/self-serve-platforms.md
  archived/airnode/v0.3/guides/smart-contracts-platform/is-my-platform-compatible.md
  archived/airnode/v0.3/guides/smart-contracts-platform/self-serve-integration.md
  archived/airnode/v0.3/self-serve-platforms.md
  archived/airnode/v0.4/self-serve-platforms.md
  archived/airnode/v0.5/self-serve-platforms.md
Labels: v0.2, v0.3, v0.4, v0.5

#661 AN- 471: Do not allow dashes in variable names
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/reference/deployment-files/aws-env.md
  docs/airnode/v0.4/reference/deployment-files/secrets-env.md
  docs/airnode/v0.4/reference/examples/aws-env.md
  docs/airnode/v0.4/reference/examples/secrets-env.md
  docs/airnode/v0.4/reference/templates/aws-env.md
  docs/airnode/v0.4/reference/templates/secrets-env.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/reference/deployment-files/aws-env.md
  docs/airnode/v0.5/reference/deployment-files/secrets-env.md
  docs/airnode/v0.5/reference/examples/aws-env.md
  docs/airnode/v0.5/reference/examples/secrets-env.md
  docs/airnode/v0.5/reference/templates/aws-env.md
  docs/airnode/v0.5/reference/templates/secrets-env.md
Labels: enhancement, v0.4, v0.5

#662 Component tip boxes now use vuepress css
  docs/.vuepress/components/DeployerPermissionsWarning.vue
  docs/.vuepress/components/airnode/DeployerPermissionsWarning.vue
  docs/.vuepress/components/airnode/DesignatedWalletWarning.vue
  docs/.vuepress/components/airnode/SponsorWalletWarning.vue
  docs/.vuepress/components/airnode/WarningSimultaneousDeployments.vue
  docs/airnode/pre-alpha/guides/requester/creating-a-requester.md
  docs/airnode/pre-alpha/protocols/request-response/designated-wallet.md
  docs/airnode/v0.2/concepts/sponsor.md
  docs/airnode/v0.2/grp-developers/fees.md
  docs/airnode/v0.2/grp-developers/requesters-sponsors.md
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.2/grp-providers/tutorial/README.md
  docs/airnode/v0.3/concepts/sponsor.md
  docs/airnode/v0.3/grp-developers/fees.md
  docs/airnode/v0.3/grp-developers/requesters-sponsors.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/concepts/sponsor.md
  docs/airnode/v0.4/grp-developers/fees.md
  docs/airnode/v0.4/grp-developers/requesters-sponsors.md
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/concepts/sponsor.md
  docs/airnode/v0.5/grp-developers/fees.md
  docs/airnode/v0.5/grp-developers/requesters-sponsors.md
  docs/airnode/v0.5/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: enhancement, v0.2, pre-alpha, v0.3, v0.4, v0.5

#663 BEC-220 v0.2 setup
  docs/.vuepress/components/VersionWarning.vue
  docs/.vuepress/config.js
  docs/beacon/v0.2/README.md
  docs/beacon/v0.2/assets/diagrams/beacon-airnode.drawio
  docs/beacon/v0.2/assets/diagrams/dapi-beacons.drawio
  docs/beacon/v0.2/assets/diagrams/dapp-beacon.drawio
  docs/beacon/v0.2/assets/images/beacon-airnode.png
  docs/beacon/v0.2/assets/images/dapi-beacons.png
  docs/beacon/v0.2/assets/images/dapp-beacon.png
  docs/beacon/v0.2/assets/images/monitor.png
  docs/beacon/v0.2/functions/README.md
  docs/beacon/v0.2/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.2/functions/read-beacon.md
  docs/beacon/v0.2/functions/reader-can-read-beacon.md
  docs/beacon/v0.2/functions/request-beacon-update.md
  docs/beacon/v0.2/introduction/hackathon.md
  docs/beacon/v0.2/introduction/why-use-beacons.md
  docs/beacon/v0.2/reference/amberdata.json
  docs/beacon/v0.2/reference/beacon-ids.md
  docs/beacon/v0.2/reference/beacon-scheme.md
  docs/beacon/v0.2/reference/contract-addresses.md
  docs/beacon/v0.2/sidebar.js
  package.json
Labels: enhancement

#664 Merge the Signed Data gateway in the http-gateways.md doc
  archived/airnode/v0.5/http-gateway.md
  docs/.vuepress/components/airnode/DeployerPermissionsWarning.vue
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.2/grp-providers/tutorial/README.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/assets/diagrams/gateway.drawio
  docs/airnode/v0.5/assets/images/gateway.png
  docs/airnode/v0.5/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/README.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/http-gateways.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/reference/deployment-files/receipt-json.md
  docs/airnode/v0.5/sidebar.js
Labels: v0.5

#666 Disable HTTP Signed Data Gateway for tutorials
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.5.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.5.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.5.zip
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/secrets.env
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/secrets.env
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/secrets.env
Labels: corrections, v0.5

#667 Incorrect paths to code sample includes
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/aws-env.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/secrets-env.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/secrets-env.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/secrets-env.md
Labels: corrections, v0.5

#668 Revive minConfirmations for v0.5
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/examples/config-cloud.json
  docs/airnode/v0.5/reference/examples/config-local.json
  docs/airnode/v0.5/reference/templates/config-json.md
Labels: v0.5

#669 triggers.http json path incorrect
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: corrections, v0.4, v0.5

#670 Updated blog posts for medium
  docs/.vuepress/blog-posts.json
Labels: enhancement

#671 Add diagram and small changes to the content of heartbeat.md
  docs/airnode/v0.5/assets/diagrams/heartbeat.drawio
  docs/airnode/v0.5/assets/images/heartbeat.png
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/heartbeat.md
Labels: enhancement, v0.5

#672 Reference doc for cloud resurces
  docs/airnode/v0.5/reference/cloud-resources.md
  docs/airnode/v0.5/sidebar.js
Labels: enhancement, v0.5

#673 AN607 signed gateway removal
  .vscode/settings.json
  docs/.vuepress/components/airnode/DeleteAirnodeAws.vue
  docs/.vuepress/components/airnode/DeleteAirnodeGcp.vue
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: corrections, enhancement, v0.2, v0.3, v0.4, v0.5

#676 GCP project setup changes
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: enhancement, v0.5

#677 20220318.1-beacons
  docs/.vuepress/api-providers.json
  docs/.vuepress/components/beacons/browser/BeaconItem.vue
  docs/.vuepress/components/beacons/browser/BeaconList.vue
  docs/.vuepress/components/beacons/browser2/BeaconItem.vue
  docs/.vuepress/components/beacons/browser2/BeaconList.vue
  docs/beacon/v0.1/reference/beacon-ids.md
  docs/beacon/v0.2/introduction/hackathon.md
  docs/beacon/v0.2/reference/beacon-browser.md
  docs/beacon/v0.2/reference/beacon-scheme.md
  docs/beacon/v0.2/reference/monitor.md
  docs/beacon/v0.2/sidebar.js
Labels: enhancement

#678 20220321 beacons browser
  docs/.vuepress/components/beacons/browser/BeaconItem.vue
  docs/.vuepress/components/beacons/browser/BeaconList.vue
  docs/.vuepress/components/beacons/browser2/BeaconDetails.vue
  docs/.vuepress/components/beacons/browser2/BeaconItem.vue
  docs/.vuepress/components/beacons/browser2/BeaconList.vue
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: enhancement

#679 AN625 release Airnode v0.5 docs
  docs/.vuepress/components/DockerImageVersions.vue
  docs/.vuepress/config.js
  docs/airnode/v0.5/concepts/README.md
  docs/airnode/v0.5/concepts/requester.md
  docs/airnode/v0.5/grp-developers/call-an-airnode.md
  docs/airnode/v0.5/grp-developers/using-templates.md
  docs/airnode/v0.5/grp-providers/docker/admin-cli-image.md
  docs/airnode/v0.5/grp-providers/docker/client-image.md
  docs/airnode/v0.5/grp-providers/docker/deployer-image.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.5/grp-providers/tutorial/README.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.5/reference/examples/config-json.md
  docs/airnode/v0.5/reference/packages/README.md
  docs/airnode/v0.5/reference/packages/adapter.md
  docs/airnode/v0.5/reference/packages/admin-cli.md
  docs/airnode/v0.5/reference/packages/airnode-abi.md
  docs/airnode/v0.5/reference/packages/deployer.md
  docs/airnode/v0.5/reference/packages/validator.md
  docs/airnode/v0.5/reference/specifications/airnode-abi-specifications.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/beacon/v0.2/functions/request-beacon-update.md
  docs/dev/release-notes.md
  docs/dev/sidebar.js
  docs/ois/v1.0.0/README.md
  docs/ois/v1.0.0/ois-template.md
  docs/ois/v1.0.0/ois.md
  docs/ois/v1.0.0/reserved-parameters.md
Labels: v0.5

#637 Add descriptions to landing page buttons
  docs/.vuepress/components/DocumentSetButtons.vue
  docs/.vuepress/components/Home.vue
  docs/README.md
Labels: enhancement

#681 20220322 adjustments corrections
  docs/.vuepress/enhanceApp.js
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/api-security.md
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: v0.5

#682 20220322 beacon list new tag
  docs/.vuepress/api-providers.json
  docs/.vuepress/components/Grafana.vue
  docs/.vuepress/components/beacons/browser/BeaconList.vue
  docs/.vuepress/components/beacons/browser2/BeaconDetails.vue
  docs/.vuepress/components/beacons/browser2/BeaconItem.vue
  docs/.vuepress/components/beacons/browser2/BeaconList.vue
  docs/.vuepress/components/beacons/browser2/BeaconModal.vue
  docs/.vuepress/components/beacons/browser2/chart_line.png
  docs/.vuepress/components/beacons/browser2/graph_fork.png
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: corrections

#685 All changes related to Beacons v0.2
  .vscode/settings.json
  archived/beacons/request-beacon-update.md
  docs/.vuepress/api-providers.json
  docs/.vuepress/components/Grafana.vue
  docs/.vuepress/components/beacons/browser2/BeaconDetails.vue
  docs/.vuepress/components/beacons/browser2/BeaconItem.vue
  docs/.vuepress/components/beacons/browser2/BeaconList.vue
  docs/.vuepress/components/beacons/browser2/BeaconModal.vue
  docs/.vuepress/components/beacons/browser2/BeaconOverlay.vue
  docs/.vuepress/components/beacons/browser2/BeaconOverlayValue.vue
  docs/.vuepress/public/img/marching-balls.gif
  docs/.vuepress/public/img/refresh-icon.png
  docs/beacon/v0.2/functions/README.md
  docs/beacon/v0.2/reference/beacon-scheme.md
  docs/beacon/v0.2/sidebar.js
Labels: enhancement

#687 20220328 beacons
  docs/.vuepress/api-providers.json
  docs/.vuepress/components/beacons/browser2/BeaconDetails.vue
  docs/.vuepress/components/beacons/browser2/BeaconItem.vue
  docs/.vuepress/components/beacons/browser2/BeaconList.vue
  docs/.vuepress/components/beacons/browser2/BeaconOverlay.vue
  docs/.vuepress/components/beacons/browser2/BeaconOverlayValue.vue
  docs/.vuepress/components/beacons/browser2/chart_line.png
  docs/.vuepress/components/beacons/browser2/graph_fork.png
Labels: corrections, enhancement

#688 20220328 http gateway link
  docs/airnode/v0.5/grp-developers/requesters-sponsors.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
Labels: corrections

#690 Add deployment timestamp to receipt.json
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.6/reference/deployment-files/receipt-json.md
Labels: enhancement, v0.6
