Repository api3dao/api3-docs, pull requests merged in 2022-01, with the labels that each got.

#516 AN384 proposals
  docs/dao-members/contract-architecture/README.md
  docs/dao-members/contract-architecture/voting.md
  docs/dao-members/dashboard/proposals.md
Labels: enhancement, v0.4

#519 Bug in docs set component.
  docs/.vuepress/components/DocumentSets.vue
Labels: corrections, v0.4

#520 BEC73.5 diagrams
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/assets/diagrams/beacon-airnode.drawio
  docs/beacon/v0.1/assets/diagrams/dapi-beacons.drawio
  docs/beacon/v0.1/assets/diagrams/dapp-beacon.drawio
  docs/beacon/v0.1/assets/images/beacon-airnode.png
  docs/beacon/v0.1/assets/images/dapi-beacons.png
  docs/beacon/v0.1/assets/images/dapp-beacon.png
  docs/beacon/v0.1/sidebar.js
Labels: corrections, enhancement, v0.4

#521 Two broken links from PR: 517 - testable flag.
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
Labels: corrections, v0.4

#522 20210115.1 corrections
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.3.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.3.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.3.zip
  docs/.vuepress/redirects
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/src/config.json
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.3/reference/packages/validator.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/packages/validator.md
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/functions/request-beacon-update.md
Labels: v0.4

#523 20210107 linkvalidator ignore list
  docs/airnode/v0.2/grp-providers/tutorial/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/dao-members/README.md
  docs/dao-members/dashboard/README.md
  libs/link-validator.js
Labels: v0.4

#524 BEC73 indefinite whitelist count templateid
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/ois/v1.0.0/example.json
  docs/ois/v1.0.0/example.md
  docs/ois/v1.0.0/ois.md
  docs/ois/v1.0.0/sidebar.js
  docs/ois/v1.0.0/structure/README.md
Labels: v0.4

#528 BEC100 indefinite whitelist by templateid
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/request-beacon-update.md
Labels: v0.4

#531 20220111 beacons cleanup.1
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
Labels: v0.4

#538 20220112 beacon content.1
  .vscode/settings.json
  docs/.vuepress/components/DocumentSetButtons.vue
  docs/.vuepress/components/DocumentSets.vue
  docs/beacon/v0.1/README.md
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/functions/reader-can-read-beacon.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/beacon/v0.1/introduction/hackathon.md
  docs/beacon/v0.1/introduction/why-use-beacons.md
  docs/beacon/v0.1/reference/beacon-catalog.md
  docs/beacon/v0.1/reference/contract-addresses.md
  docs/beacon/v0.1/reference/ids.md
  docs/beacon/v0.1/sidebar.js
Labels: v0.4

#541 20220117 beacon catalog.1
  .vscode/settings.json
  archived/beacons/BeaconCatalog.vue
  archived/beacons/hackathonBeaconIds.json
  docs/.vuepress/components/BlogPosts.vue
  docs/.vuepress/config.js
  docs/beacon/v0.1/introduction/hackathon.md
  docs/beacon/v0.1/reference/beacon-catalog.md
  docs/beacon/v0.1/reference/beacon-ids.md
  docs/beacon/v0.1/reference/contract-addresses.md
  docs/beacon/v0.1/sidebar.js
  package.json
  yarn.lock
Labels: v0.4

#544 2022019 corrections
  docs/beacon/v0.1/reference/amberdata.json
  docs/beacon/v0.1/reference/beacon-ids.md
Labels: v0.4

#543 AN-497: Unify "scheme/schema" spelling to "scheme"
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/api-security.md
Labels: v0.4

#545 BEC98 contract addresses and beaconIds
  docs/.vuepress/public/img/Beacons-icon-black.png
  docs/.vuepress/public/img/Beacons-icon-green.png
  docs/.vuepress/public/img/Beacons-icon-white.png
  docs/.vuepress/public/img/beacon-active.png
  docs/.vuepress/public/img/beacon-inactive.png
  docs/.vuepress/public/img/workers-32.png
  docs/.vuepress/public/img/workers-48.png
  docs/.vuepress/public/img/workers-64.png
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/functions/reader-can-read-beacon.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/beacon/v0.1/introduction/hackathon.md
  docs/beacon/v0.1/reference/amberdata.json
  docs/beacon/v0.1/reference/beacon-ids.md
  docs/beacon/v0.1/reference/contract-addresses.md
  docs/beacon/v0.1/reference/ids.md
  docs/dev/versioning.md
Labels: v0.4

#550 BEC116 Update to the hackathon page
  .vscode/settings.json
  docs/airnode/v0.4/grp-developers/README.md
  docs/airnode/v0.4/grp-developers/call-an-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/beacon/v0.1/introduction/hackathon.md
Labels: v0.4

#551 Add section for the Beacon monitor.
  docs/beacon/v0.1/assets/images/monitor.png
  docs/beacon/v0.1/reference/beacon-ids.md
Labels: v0.4

#554 AN-502
  docs/.vuepress/public/img/info5.png
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.4.zip
  docs/.vuepress/styles/index.styl
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  libs/link-validator.js
Labels: v0.4

#555 Mention that there can be more the 1 OIS object
  docs/airnode/v0.4/reference/specifications/ois.md
  docs/airnode/v0.4/reference/templates/ois-json.md
Labels: v0.4

#558 Only mention RRP protocol on change=1 from path
  docs/airnode/v0.4/concepts/sponsor.md
Labels: corrections, v0.4

#559 Added GCP receipt file.
  docs/airnode/v0.4/reference/deployment-files/receipt-json.md
Labels: enhancement, v0.4

#562 AN458 tutorials
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.4.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.4.zip
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.3/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: v0.4

#564 20221025-beacon-list
  archived/beacons/BeaconListOrg.vue
  docs/.vuepress/components/beacons/BeaconItem.vue
  docs/.vuepress/components/beacons/BeaconList.vue
  docs/.vuepress/components/beacons/beaconInfo.json
  docs/api3/introduction/contributing.md
  docs/api3/introduction/work.md
  docs/beacon/v0.1/reference/beacon-ids.md
Labels: v0.4

#565 20220126-correction-Update input css
  docs/.vuepress/components/beacons/BeaconList.vue
Labels: corrections, v0.4

#566 AN512 simultaneous deloyments
  docs/.vuepress/components/airnode/WarningSimultaneousDeployments.vue
  docs/.vuepress/components/beacons/BeaconItem.vue
  docs/.vuepress/components/beacons/BeaconList.vue
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/reference/packages/deployer.md
Labels: enhancement, v0.4

#568 AN308 http gateway gcp support
  docs/.vuepress/public/img/info-blue-20.png
  docs/.vuepress/public/img/info-green-20.png
  docs/.vuepress/public/img/info5.png
  docs/.vuepress/public/img/info8.png
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.4.zip
  docs/.vuepress/styles/index.styl
  docs/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.4/grp-providers/guides/build-an-airnode/http-gateway.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.4/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/secrets.env
  docs/airnode/v0.4/reference/deployment-files/config-json.md
Labels: v0.4

#569 20220128 jobs badge
  docs/.vuepress/components/Navbar.vue
  docs/.vuepress/components/Versions.vue
  docs/.vuepress/components/VersionsModal.vue
  docs/.vuepress/components/api3/JobsIcon.vue
  docs/.vuepress/config.js
  docs/dev/custom-components.md
Labels: v0.4

#570 20221029 add chainapi
  .vscode/settings.json
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/img/chainapi-active.png
  docs/.vuepress/public/img/chainapi-inactive.png
  docs/chainapi/README.md
  docs/chainapi/introduction/why-use-chainapi.md
  docs/chainapi/more/README.md
  docs/chainapi/more/more-stuff.md
  docs/chainapi/sidebar.js
Labels: v0.4

#571 An518 dynamo db manual removal
  .vscode/settings.json
  docs/.vuepress/components/DeleteAirnodeAws.vue
  docs/airnode/v0.2/grp-providers/docker/deployer-image.md
  docs/airnode/v0.3/grp-providers/docker/deployer-image.md
  docs/airnode/v0.4/grp-providers/docker/deployer-image.md
Labels: v0.4

#574 AN-524 Adjustments for mobile devices.
  docs/.vuepress/components/Navbar.vue
  docs/.vuepress/components/Versions.vue
  docs/.vuepress/components/VersionsModal.vue
  docs/.vuepress/components/api3/JobsIcon.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/img/logo-only.png
Labels: corrections, v0.4
