Repository api3dao/api3-docs, pull requests merged in 2022-04, with the labels that each got.

#694 202203331 chains component
  .vscode/settings.json
  docs/.vuepress/chains.json
  docs/.vuepress/components/Overlay.vue
  docs/.vuepress/components/airnode/ContractAddresses.vue
  docs/.vuepress/components/chains/ChainItem.vue
  docs/.vuepress/components/chains/ChainList.vue
  docs/.vuepress/components/chains/ChainTest.vue
  docs/.vuepress/public/img/copy.png
  docs/airnode/v0.5/reference/airnode-addresses.md
  docs/airnode/v0.6/reference/airnode-addresses.md
  docs/beacon/v0.2/reference/chain-browser.md
  docs/beacon/v0.2/reference/contract-addresses.md
  docs/beacon/v0.2/sidebar.js
Labels: enhancement, v0.5, v0.6

#695 Copy icon appears on dev but not production
  docs/.vuepress/components/airnode/ContractAddresses.vue
Labels: corrections, v0.5, v0.6

#696 AN-639 contract address ordering
  docs/.vuepress/chains.json
  docs/.vuepress/components/airnode/ContractAddresses.vue
  docs/airnode/v0.6/README.md
  docs/airnode/v0.6/assets/diagrams/api-provider-overview-aws.drawio
  docs/airnode/v0.6/assets/diagrams/summary-airnode-2-parts.drawio
  docs/airnode/v0.6/assets/diagrams/~$api-provider-overview-aws.drawio.bkp
  docs/airnode/v0.6/assets/diagrams/~$summary-airnode-2-parts.drawio.bkp
  docs/airnode/v0.6/assets/images/api-provider-overview-aws.png
  docs/airnode/v0.6/assets/images/api-provider-overview-container.png
  docs/airnode/v0.6/assets/images/api-provider-overview-gcp.png
  docs/airnode/v0.6/assets/images/summary-airnode-2-parts.png
  docs/airnode/v0.6/grp-providers/README.md
Labels: v0.5, v0.6

#697 revert addresses for v0.5
  docs/airnode/v0.5/reference/airnode-addresses.md
Labels: corrections, v0.5

#698 ChildPage layout started - minor fixes
  docs/.vuepress/components/ChildPage.vue
  docs/.vuepress/components/Overlay.vue
  docs/.vuepress/components/chains/ChainDetail.vue
  docs/.vuepress/components/chains/ChainItem.vue
  docs/.vuepress/components/chains/ChainList.vue
  docs/.vuepress/components/chains/ChainListItem.vue
  docs/.vuepress/components/chains/ChainTest.vue
  docs/airnode/v0.2/concepts/request.md
  docs/airnode/v0.2/reference/deployment-files/config-json.md
  docs/airnode/v0.3/concepts/request.md
  docs/airnode/v0.3/reference/deployment-files/config-json.md
  docs/airnode/v0.4/concepts/request.md
  docs/airnode/v0.4/reference/deployment-files/config-json.md
  docs/airnode/v0.4/reference/packages/validator.md
  docs/airnode/v0.5/concepts/request.md
  docs/airnode/v0.5/reference/deployment-files/config-json.md
  docs/airnode/v0.5/reference/specifications/reserved-parameters.md
  docs/airnode/v0.6/concepts/request.md
  docs/airnode/v0.6/reference/deployment-files/config-json.md
  docs/airnode/v0.6/reference/specifications/reserved-parameters.md
  docs/beacon/v0.2/reference/chain-browser.md
  docs/beacon/v0.2/reference/chain-detail.md
Labels: corrections, v0.6

#700 Phase 3 chain deployments
  .vscode/settings.json
  docs/.vuepress/chains.json
Labels: enhancement, v0.6

#702 Missing triggers.http values
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.5.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.6.zip
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
Labels: corrections, v0.5, v0.6

#703 20220413 airnode wallet mnemonic rework
  docs/airnode/v0.5/concepts/airnode.md
  docs/airnode/v0.5/reference/packages/admin-cli.md
  docs/airnode/v0.6/concepts/airnode.md
  docs/airnode/v0.6/reference/packages/admin-cli.md
Labels: corrections, enhancement, v0.5, v0.6

#704 Fix encode value for MyBytes32
  docs/airnode/v0.4/reference/specifications/airnode-abi-specifications.md
  docs/airnode/v0.5/reference/specifications/airnode-abi-specifications.md
  docs/airnode/v0.6/reference/specifications/airnode-abi-specifications.md
Labels: corrections, v0.4, v0.5, v0.6

#705 Add "Why power Beacons?" and related changes
  docs/beacon/v0.2/assets/diagrams/why-power-beacons.drawio
  docs/beacon/v0.2/assets/diagrams/~$why-power-beacons.drawio.bkp
  docs/beacon/v0.2/assets/images/why-power-beacons.png
  docs/beacon/v0.2/introduction/why-power.md
  docs/beacon/v0.2/introduction/why-use-beacons.md
  docs/beacon/v0.2/sidebar.js
Labels: enhancement

#706 Fix links using .html rather than .md
  docs/airnode/v0.5/concepts/airnode.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.6/concepts/airnode.md
Labels: enhancement

#707 AN670-add-fulfillmentGasLimit
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.6.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.6.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.6.zip
  docs/airnode/v0.5/concepts/chain-providers.md
  docs/airnode/v0.5/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.6/concepts/chain-providers.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.6/reference/deployment-files/config-json.md
  docs/airnode/v0.6/reference/examples/config-cloud.json
  docs/airnode/v0.6/reference/examples/config-local.json
  docs/airnode/v0.6/reference/templates/config-json.md
Labels: corrections, enhancement, v0.5, v0.6

#708 fulfillmentGasLimit permanent failure
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.6/reference/deployment-files/config-json.md
Labels: enhancement, v0.6

#709 Utilize the new chainNames key in references.json
  archived/airnode/v0.6/chains.json
  docs/.vuepress/components/airnode/ContractAddresses.vue
Labels: enhancement, v0.6

#710 20220418 titlespan cleanup
  docs/.vuepress/components/TitleSpan.vue
  docs/airnode/v0.6/reference/cloud-resources.md
Labels: enhancement

#711 Point to master until v0.6 release
  docs/.vuepress/components/airnode/ContractAddresses.vue
Labels: corrections, v0.6

#712 20220419 power beacons doc
  docs/beacon/v0.1/functions/README.md
  docs/beacon/v0.1/functions/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.1/functions/read-beacon.md
  docs/beacon/v0.1/functions/reader-can-read-beacon.md
  docs/beacon/v0.1/functions/request-beacon-update.md
  docs/beacon/v0.1/reference/beacon-scheme.md
  docs/beacon/v0.2/README.md
  docs/beacon/v0.2/developers/README.md
  docs/beacon/v0.2/developers/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.2/developers/read-beacon.md
  docs/beacon/v0.2/developers/reader-can-read-beacon.md
  docs/beacon/v0.2/introduction/why-power.md
  docs/beacon/v0.2/reference/beacon-scheme.md
  docs/beacon/v0.2/sidebar.js
Labels: corrections, enhancement, v0.6

#713 Adjust contract name with V0
  docs/airnode/v0.6/README.md
  docs/airnode/v0.6/concepts/README.md
  docs/airnode/v0.6/concepts/request.md
  docs/airnode/v0.6/concepts/sponsor.md
  docs/airnode/v0.6/grp-developers/README.md
  docs/airnode/v0.6/grp-developers/call-an-airnode.md
  docs/airnode/v0.6/grp-developers/using-templates.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.6/reference/packages/admin-cli.md
  docs/beacon/v0.2/README.md
  docs/beacon/v0.2/developers/README.md
  docs/beacon/v0.2/developers/beaconid-reader-whiteliststatus.md
  docs/beacon/v0.2/developers/read-beacon.md
  docs/beacon/v0.2/developers/reader-can-read-beacon.md
  docs/beacon/v0.2/reference/contract-addresses.md
Labels: enhancement, v0.6

#716 Prep work for the Beacon chains list.
  docs/.vuepress/components/beacons/ChainsList.vue
  docs/beacon/v0.2/reference/chain-browser.md
  docs/beacon/v0.2/reference/chains.md
  docs/beacon/v0.2/sidebar.js
Labels: enhancement

#719 Slight modification to GCP tutorial step 4
  docs/airnode/v0.5/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-gcp/README.md
Labels: corrections, enhancement, v0.5, v0.6

#720 Fix location of fulfillmentGasLimit
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.6.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.6.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.6.zip
  docs/airnode/v0.6/concepts/chain-providers.md
  docs/airnode/v0.6/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws-v0.6.zip
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config/config.json
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container-v0.6.zip
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config/config.json
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp-v0.6.zip
  docs/airnode/v0.6/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config/config.json
  docs/airnode/v0.6/reference/deployment-files/config-json.md
  docs/airnode/v0.6/reference/examples/config-cloud.json
  docs/airnode/v0.6/reference/templates/config-json.md
Labels: corrections, v0.6

#721 Adjust language of why power beacons
  docs/beacon/v0.2/introduction/why-power.md
Labels: enhancement

#723 Beacon reader example
  .vscode/settings.json
  docs/beacon/v0.1/introduction/hackathon.md
  docs/beacon/v0.2/developers/README.md
  docs/beacon/v0.2/introduction/why-power.md
Labels: corrections, enhancement

#725 Update signed gateway response example
  docs/airnode/v0.7/grp-providers/guides/build-an-airnode/http-gateways.md
Labels: v0.7

#726 An183 fix older beacon reader
  docs/.vuepress/components/beacons/browser2/BeaconChildDetail.vue
  docs/.vuepress/components/beacons/browser2/BeaconList.vue
  docs/beacon/v0.2/developers/README.md
Labels: enhancement
