Repository api3dao/api3-docs, pull requests merged in 2023-04, with the labels that each got.

#1233 update quintessence minConfirmations
  docs/qrng/reference/chains.md
Labels: QRNG, ★ migrate, ✔︎ mIgrated

#1237 v0.11 tutorial zip files not needed
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.11.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.11.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.11.zip
  docs/airnode/v0.8/reference/migration.md
  docs/dev/link-validator.md
  docs/qrng/guides/remix-example.md
Labels: v0.11

#1239 Hide older version banner
  docs/.vuepress/components/VersionWarning.vue
  docs/.vuepress/public/CNAME
  docs/README.md
  libs/Page.vue
  package.json
Labels: corrections, enhancement
