Repository api3dao/api3-docs, pull requests merged in 2023-02, with the labels that each got.

#1179 added examples to skip API calls and use pre-post-processing
  docs/airnode/v0.10/reference/migration.md
  docs/ois/v1.4/ois.md
  docs/ois/v1.4/processing.md
Labels: OIS, ★ migrate, ✔︎ mIgrated

#1180 Remove ChainAPI
  docs/.vuepress/components/DocumentSetButtons.vue
  docs/.vuepress/components/DocumentSets.vue
  docs/.vuepress/config.js
  docs/chainapi/README.md
  docs/chainapi/assets/diagrams/.$what-overview.drawio.bkp
  docs/chainapi/assets/diagrams/.$what-overview.drawio.dtmp
  docs/chainapi/assets/diagrams/.$why-overview.drawio.bkp
  docs/chainapi/assets/diagrams/what-overview.drawio
  docs/chainapi/assets/diagrams/why-overview.drawio
  docs/chainapi/assets/images/Login.png
  docs/chainapi/assets/images/choose-wallet.png
  docs/chainapi/assets/images/connect.png
  docs/chainapi/assets/images/deployment-status.png
  docs/chainapi/assets/images/deployment-statuses-diagram.png
  docs/chainapi/assets/images/integrate-api.png
  docs/chainapi/assets/images/new-deployment.png
  docs/chainapi/assets/images/what-overview.png
  docs/chainapi/assets/images/why-overview.png
  docs/chainapi/introduction/why-use-chainapi.md
  docs/chainapi/reference/example-files/README.md
  docs/chainapi/reference/example-files/aws.env
  docs/chainapi/reference/example-files/aws.md
  docs/chainapi/reference/example-files/config.json
  docs/chainapi/reference/example-files/config.md
  docs/chainapi/reference/example-files/overview.md
  docs/chainapi/reference/example-files/secrets.env
  docs/chainapi/reference/example-files/secrets.md
  docs/chainapi/reference/terms.md
  docs/chainapi/sidebar.js
  docs/chainapi/user-guides/Import&Export.md
  docs/chainapi/user-guides/README.md
  docs/chainapi/user-guides/deployments.md
  docs/chainapi/user-guides/integrations.md
  docs/chainapi/user-guides/registration.md
  docs/chainapi/user-guides/workspaces.md
  docs/dev/theme.md
  docs/dev/versioning.md
Labels: ChainAPI

#1177 feat: describe new _minConfirmations reserved parameter
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.10/reference/examples/config-cloud.json
  docs/airnode/v0.10/reference/examples/config-local.json
  docs/airnode/v0.10/reference/migration.md
  docs/ois/v1.4/example.json
  docs/ois/v1.4/ois.md
  docs/ois/v1.4/reserved-parameters.md
Labels: OIS, v0.10, ★ migrate, ✔︎ mIgrated

#1183 update chains.json for new chains
  docs/.vuepress/chains.json
Labels: v0.10, ★ migrate

#1191 Change tutorial file to DEBUG for logs
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.10.zip
  docs/.vuepress/public/zip-files/quick-deploy-aws-v0.11.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.10.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.11.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.10.zip
  docs/.vuepress/public/zip-files/quick-deploy-gcp-v0.11.zip
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config.json
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config.json
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp-v0.10.zip
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config.json
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-aws/README.md
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-aws/config-json.md
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-aws/src/quick-deploy-aws/config.json
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-container/config-json.md
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config.json
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-gcp/README.md
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-gcp/config-json.md
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp-v0.10.zip
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-gcp/src/quick-deploy-gcp/config.json
  docs/dev/versioning.md
Labels: corrections, v0.10, ★ migrate, ✔︎ mIgrated, v0.11

#1192 fix: make validator package repo link clickable
  docs/airnode/v0.10/reference/packages/validator.md
  docs/airnode/v0.11/reference/packages/validator.md
  docs/airnode/v0.9/reference/packages/validator.md
Labels: v0.9, v0.10, ★ migrate, v0.11

#1196 1195 quick deploy node settings.stage char limit
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.10.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.11.zip
  docs/.vuepress/public/zip-files/quick-deploy-container-v0.9.zip
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.10/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config.json
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.11/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config.json
  docs/airnode/v0.9/grp-providers/tutorial/quick-deploy-container/README.md
  docs/airnode/v0.9/grp-providers/tutorial/quick-deploy-container/src/quick-deploy-container/config.json
Labels: corrections, v0.9, v0.10, ★ migrate, v0.11

#1198 fulfillmentGasLimit - 5000000
  docs/airnode/v0.10/reference/chain-idiosyncrasies.md
  docs/airnode/v0.11/reference/chain-idiosyncrasies.md
  docs/airnode/v0.7/reference/chain-idiosyncrasies.md
  docs/airnode/v0.8/reference/chain-idiosyncrasies.md
  docs/airnode/v0.9/reference/chain-idiosyncrasies.md
Labels: corrections, v0.7, v0.8, v0.9, v0.10, ★ migrate, ✔︎ mIgrated, v0.11

#1200 20230216 add toc
  docs/airnode/v0.10/reference/chain-idiosyncrasies.md
  docs/airnode/v0.10/reference/migration.md
  docs/airnode/v0.11/reference/chain-idiosyncrasies.md
Labels: enhancement, v0.10, v0.11

#1202 create OIS v2.0 pages
  .github/workflows/check-links-imgs.yaml
  docs/.vuepress/config.js
  docs/ois/v2.0/README.md
  docs/ois/v2.0/assets/diagrams/ois-overview-extended.drawio
  docs/ois/v2.0/assets/images/ois-overview-extended.png
  docs/ois/v2.0/example.json
  docs/ois/v2.0/example.md
  docs/ois/v2.0/ois-template.md
  docs/ois/v2.0/ois.md
  docs/ois/v2.0/processing.md
  docs/ois/v2.0/reserved-parameters.md
  docs/ois/v2.0/sidebar.js
Labels: OIS, ★ migrate

#1205 20230217 corrections
  archived/operations/README.md
  archived/operations/assets/images/api3-operations-diagram.jpg
  archived/operations/deployment_usage.md
  archived/operations/development_usage.md
  archived/operations/integrating_new_provider.md
  archived/operations/reference.md
  archived/operations/sidebar.js
  archived/operations/structure.md
  docs/.vuepress/config.js
  docs/airnode/v0.10/concepts/endpoint.md
  docs/airnode/v0.10/concepts/request.md
  docs/airnode/v0.10/grp-developers/call-an-airnode.md
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.10/grp-providers/tutorial/README.md
  docs/airnode/v0.10/reference/deployment-files/config-json.md
  docs/airnode/v0.10/reference/packages/README.md
  docs/airnode/v0.10/reference/packages/adapter.md
  docs/airnode/v0.10/reference/specifications/ois.md
  docs/airnode/v0.10/reference/specifications/reserved-parameters.md
  docs/airnode/v0.10/reference/templates/ois-json.md
  docs/airnode/v0.11/concepts/endpoint.md
  docs/airnode/v0.11/concepts/request.md
  docs/airnode/v0.11/grp-developers/call-an-airnode.md
  docs/airnode/v0.11/grp-providers/guides/build-an-airnode/api-integration.md
  docs/airnode/v0.11/grp-providers/guides/build-an-airnode/configuring-airnode.md
  docs/airnode/v0.11/grp-providers/tutorial/README.md
  docs/airnode/v0.11/reference/deployment-files/config-json.md
  docs/airnode/v0.11/reference/migration.md
  docs/airnode/v0.11/reference/packages/README.md
  docs/airnode/v0.11/reference/packages/adapter.md
  docs/airnode/v0.11/reference/specifications/ois.md
  docs/airnode/v0.11/reference/specifications/reserved-parameters.md
  docs/airnode/v0.11/reference/templates/ois-json.md
  docs/api3/introduction/work.md
  docs/ois/v2.0/README.md
  docs/ois/v2.0/example.json
  docs/ois/v2.0/ois-template.md
  docs/ois/v2.0/ois.md
  docs/ois/v2.0/processing.md
  docs/ois/v2.0/reserved-parameters.md
Labels: OIS, ★ migrate, v0.11

#1207 Update OIS `v2.0` to Node 18
  docs/ois/v2.0/ois.md
  docs/ois/v2.0/processing.md
Labels: OIS, ★ migrate

#1209 remove airnodeAddressShort and use deploymentId
  docs/.vuepress/components/airnode/DeleteAirnodeAws.vue
  docs/airnode/v0.10/grp-providers/docker/deployer-image.md
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/monitoring-airnode.md
  docs/airnode/v0.10/reference/deployment-files/receipt-json.md
  docs/airnode/v0.11/grp-providers/docker/deployer-image.md
  docs/airnode/v0.11/grp-providers/guides/build-an-airnode/deploying-airnode.md
  docs/airnode/v0.11/grp-providers/guides/build-an-airnode/monitoring-airnode.md
  docs/airnode/v0.11/reference/deployment-files/receipt-json.md
Labels: corrections, v0.10, ★ migrate, v0.11

#1210 medium posts
  docs/.vuepress/blog-posts.json
Labels: enhancement
