Repository api3dao/api3-docs, pull requests merged in 2023-01, with the labels that each got.

#1157 Define QRNG, lowercase BYOG, clarify warning
  docs/qrng/README.md
  docs/qrng/guides/remix-example.md
Labels: QRNG

#1168 Describe requester passing reserved parameter value
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/api-integration.md
  docs/ois/v1.0/ois.md
  docs/ois/v1.1/ois.md
  docs/ois/v1.2/ois.md
  docs/ois/v1.3/ois.md
  docs/ois/v1.4/ois.md
  docs/ois/v1.4/reserved-parameters.md
Labels: ★ migrate

#1169 Add logs directory to deployer arguments
  docs/airnode/v0.10/grp-providers/docker/deployer-image.md
  docs/airnode/v0.10/reference/packages/deployer.md
Labels: v0.10, ★ migrate

#1165 Replace operations S3 chains source with operations api
  archived/components/beacons/browser2/BeaconList2.vue
  docs/.vuepress/components/dapis/browsers/DapiList.vue
  docs/.vuepress/components/dapis/chains/ChainsList.vue
  package.json
Labels: ★ migrate

#1170 Add airnode-deployer `rollback` command
  docs/airnode/v0.10/grp-providers/docker/deployer-image.md
  docs/airnode/v0.10/reference/packages/deployer.md
Labels: v0.10, ★ migrate

#1171 20230122 fix dapis chain dsource
  archived/components/chains-deprecated/ChainDetail.vue
  archived/components/chains-deprecated/ChainList.vue
  archived/components/chains-deprecated/ChainListItem.vue
  archived/components/dapis/browsers/DapiDetails.vue
  archived/components/dapis/browsers/DapiList.vue
  archived/components/dapis/browsers/DapiValue.vue
  docs/.vuepress/components/dapis/chains/ChainsItem.vue
  docs/.vuepress/components/dapis/chains/ChainsList.vue
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/heartbeat.md
  docs/airnode/v0.10/reference/deployment-files/secrets-env.md
  package.json
Labels: dAPIs, ★ migrate, ✔︎ mIgrated

#1173 JSON obj poorly formatted
  docs/airnode/v0.10/grp-providers/guides/build-an-airnode/heartbeat.md
Labels: corrections, v0.10, ★ migrate, ✔︎ mIgrated

#1172 Add migration guide for Airnode v0.10
  docs/airnode/v0.10/reference/migration.md
  docs/airnode/v0.10/sidebar.js
Labels: v0.10, ★ migrate

#1174 fix: minor updates to v0.10 migration guide
  docs/airnode/v0.10/reference/migration.md
Labels: v0.10, ★ migrate

#1178 Escape separators: _path="very\\,strange\\.key"
  docs/airnode/v0.3/reference/specifications/reserved-parameters.md
  docs/ois/v1.0/reserved-parameters.md
  docs/ois/v1.1/reserved-parameters.md
  docs/ois/v1.2/reserved-parameters.md
  docs/ois/v1.3/reserved-parameters.md
  docs/ois/v1.4/reserved-parameters.md
Labels: OIS, ★ migrate, ✔︎ mIgrated
